### ISSUE TITLE
Add Pulsar to the "Comparison of HTML editors" Wikipedia page

### ISSUE THREAD

**Issue by Korb** [pulsar-edit/pulsar#1021]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Currently, the "[Comparison of HTML editors](https://en.wikipedia.org/wiki/Comparison_of_HTML_editors)" page on Wikipedia lists 40 applications for editing web code: Amaya, Apache OpenOffice, Aptana Studio, Arachnophilia, Atom, Bluefish, BlueGriffon, Brackets, Claris Homepage, Coda, Codelobster, CoffeeCup HTML Editor, Contribute, CudaText, Dreamweaver, EZGenerator, Freeway, GoLive, Google Web Designer, HTML-Kit, KompoZer, LibreOffice, Maqetta, Microsoft Expression Web, Microsoft FrontPage Express, Microsoft Office FrontPage, Microsoft SharePoint Designer, Microsoft Visual Studio Code, Microsoft Visual Web Developer, Mobirise, Mozilla Composer, Nvu, OpenOffice.org, oXygenXML Editor[d], Quanta Plus, RocketCake, SeaMonkey Composer, TextMate, TOWeb, and WebStorm IDE.

### What benefits does this feature provide?

Some users, myself included, often choose their tools using filters. Wikipedia offers limited search capabilities using filters, but the page does include feature tables that can be easily copied into a spreadsheet processor and then sorted and filtered to produce a list of tools for final testing. The Pulsar application is not included in these tables. Accordingly, users will either not know about the existence of Pulsar, or will be unaware of its advantages over alternative products.

### Any alternatives?

No.

**Comment by DeeDeeG** [comment]
Hi, thanks for the suggestion.

Folks involved with a subject are discouraged from being involved with editing Wikipedia about that subject, for example due to https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest.

So, my interpretation/conclusion is that Pulsar team members should not edit Wikipedia about Pulsar.

If you think it makes a good addition, per your own judgment, then you can do so yourself (Wikipedia encourages people to make the change they'd like to see, e.g. https://en.wikipedia.org/wiki/Wikipedia:Be_bold). Or, a little more conservative approach if you're unsure would be to raise the subject on a given article's Talk page and let others decide whether/how precisely to make an edit. If you feel you have any affiliation with the Pulsar project, please be transparent about that and mention it somewhere whenever interacting with Wikipedia about Pulsar.

Speaking for myself personally, the independence and verifiability of information on Wikipedia, as well as its overall operating principles, are very important to me. I'm sure the rest of the team generally agrees. So, yeah. Not something I'm going to touch in terms of directly editing Wikipedia about our own project. If someone else wants to, in an appropriate manner following Wikipedia's guidelines (and ideally without particular coordination with/independent of Pulsar team), go for it. (Within reason, of course.)

Best regards,
\- DeeDeeG

**Comment by Korb** [comment]
@DeeDeeG, at least you, as a Pulsar developer, can provide some guidance on exactly what values ​​you think should be included for Pulsar in the tables. It is best to accompany the statements with links to proofs. This will prevent Wikipedia from having incorrect information about Pulsar, from asking you questions here, and from arguing about the presence or absence of certain features in discussions on the Wikipedia page. I'm not sure that directly answering the questions I asked below can be considered manipulating and abusing the opinions of Wikipedia editors to dishonestly promote their product. _Although, I, who at one time had the displeasure of communicating with the guardians of Wikipedia, will not be surprised by this._

1. Operating system support (Windows, macOS, GNU/Linux, BSD, Unix, iOS, Android)
2. Features (WYSIWYG, FTP Upload, WebDAV Upload, Server-side scripting, Shared editing, Spell checking, Templates, Templates Update Sync, Page Preview, and Form Handler)
3. Web technology support (CSS2, CSS3, Frames, Java, JavaScript, XSLT, XHTML, MathML, XForms, RSS, Atom, and XPath)
4. HTML/XHTML specification support (HTML 3.2, HTML 4.01 (strict, trans., f.set), HTML 5, XHTML 1.0 (strict, trans., f.set), XHTML 1.1, and Validating)
5. Image format support (JPEG, GIF, PNG, TIFF, and SVG)

**Comment by confused-Techie** [comment]
@Korb Thanks for opening this issue!
I do totally agree with @DeeDeeG's cautious stance on adding data to Wikipedia directly, as it's something we've avoided in other topics as well. But to the end of anyone being able to do so and just needing some valid info to add, and to that end of answering the questions you're raising, I'm happy to help provide some info, while of course not suggesting that this information be added directly to Wikipedia verbatim or at all, as that is still up to the discretion of an outside party to do so.

Some of these questions are somewhat hard to answer, since by default Pulsar may not support these features, but through the use of community package's these features could be added, but I'll go ahead and assume we should only care about the features of Pulsar and it's built-in packages.

1. Pulsar uses Electron, and with it is able to support Windows, macOS, and Linux. Pulsar is even supported on architectures like ARM and Apple Silicon.
2. I'd say to omit this section, since while some of these features are supported by built-in packages, such as `spell-check` providing Spell checking, and `markdown-preview` providing "Page Previews" it doesn't provide it for HTML, which is the purpose of the linked page. Additionally, many of these features could likely be added via community package's anyway, so saying outright no may be disingenuous. 
3. Pulsar does have built in syntax highlighting for HTML, CSS, JavaScript, and XML, if that's what this refers too.
4. There is no built in validator for any language in Pulsar, but most languages have community packages with available validators, or even some community packages that interact with any language server to provide these features for any language.
5. The built-in package `image-view` provides native support for previewing `.bmp`, `.gif`, `.ico`, `.jpeg`, `.jpg`, `.png`, `.webp`.

While I hope this helps, one of the things that might be best to do is follow what the "Atom" entry on that page does. Since Pulsar is forked directly from Atom, and much of what I've said is identical between Atom and Pulsar. For Atom on that page they listed it as an editor, and listed it's operating system support, but then didn't mention it at all in any of the supported features.

But even if you choose not to add Pulsar to this list hope this information proves useful to anyone curious about it, and it's totally up to a community member if they feel the need to add any information to Wikipedia about the project.
