### ISSUE TITLE
Maxizimized button is disabled

### ISSUE THREAD

**Issue by mirrodin71** [pulsar-edit/pulsar#1130]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Después de realizar la instalación de algunos paquetes para configurar Pulsar, este redujo su tamaño al mínimo posible. Al principio realicé las instalaciones usando la versión portable. Como ya no podía ver nada decidí hacer la instalación normal pensando que eso reiniciaría las configuraciones. Cosa que no dio resultado, por lo que procedí a desinstalar y borrar los registros usando aplicaciones de terceros.

Lo que me lleva al estado actual que tengo donde la pantalla quedó con un ancho fijo y no puedo realizar cambios en el tamaño de la pantalla.

Agradecería si pueden indicarme cómo realizar una instalación limpia de la aplicación o indicarme qué parámetros debo configurar para desbloquear el cambio de tamaño.

Anexo igualmente una captura de pantalla.
///////////////////
After installing some packages to configure Pulsar, its size was reduced to the minimum possible. Initially, I installed it using the portable version. As I could no longer see anything, I decided to do a normal installation thinking that it would reset the configurations. This did not work, so I proceeded to uninstall and delete the registry using third-party applications.

This brings me to the current state where the screen has a fixed width and I cannot change the screen size.

I would appreciate it if you could tell me how to perform a clean installation of the application or tell me what parameters I need to configure to unlock the size change.

I am also attaching a screenshot.

![pulsar](https://github.com/user-attachments/assets/decd3db8-95e4-4a24-a690-c61b3e30f664)

### Pulsar version

1.122.2024110501

### Which OS does this happen on?

🪟 Windows

### OS details

11

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Liss of additional packages installed
![pulsar02](https://github.com/user-attachments/assets/8bf355c9-1dcf-4449-a489-00ec7453b49b)
![pulsar03](https://github.com/user-attachments/assets/d0a3943b-8f87-4df5-9883-e733a15deafa)

### Additional Information:

Aun despues de la desinstalacion y eliminacion de la version portable me siguio mostrando los paquetes que se adjuntan
![pulsar02](https://github.com/user-attachments/assets/e94ef698-529c-4c96-a455-d838ddf59d92)
![pulsar03](https://github.com/user-attachments/assets/3aef8f90-f030-43eb-9b5e-fe82ede32048)

/////
Even after uninstalling and deleting the portable version, it continued to show the attached packages.

**Comment by savetheclocktower** [comment]
I don't know exactly what's causing this bug, but try this…

If you added `pulsar` to your `PATH` with the installation wizard, try running from the command line with the `--clear-window-state` flag:

```
pulsar --clear-window-state
```

If you didn't add it to your `PATH`, then navigate your command prompt to the folder in which `Pulsar.exe` resides and run that same command.

This should remove all remembered window states and sizes. Let me know if that helps.

**Comment by mirrodin71** [comment]
Hello, thank you for taking the time to answer my question. I already ran the command and it's still the same.

**Comment by mirrodin71** [comment]
Something curious happened to me. When I used the F11 button, the screen took the size of my monitor. I would like to know if anyone can tell me where I can configure the screen properties in Pulsar, as I suspect the problem is that it is disabled or some variable was changed to adjust the size in Pulsar's code.

**Comment by mirrodin71** [comment]
LOL, I managed to fix it, everything was in the configuration file _(config.cson)_. It had the following written:

> "*":
  core:
    allowWindowTransparency: true
    automaticallyUpdate: true
    themes: [
      "atom-dark-ui"
      "atom-dark-syntax"
    ]
  editor: {}
  "exception-reporting":
    userId: "..."
  "linter-ui-default":
    showPanel: true
  welcome:
    showChangeLog: false
    showOnStartup: false

Take the configuration from another computer that doesn't have the problem and replace the information. Once you restart, I can maximize the screen.

> "*":
  "exception-reporting":
    userId: "..."
  welcome:
    showChangeLog: false
    showOnStartup: false

Just to complement this, does anyone know if there is a guide on how to correctly edit what is in the config.cson file?

**Comment by savetheclocktower** [comment]
Ah. The `allowWindowTransparency` setting _might_ have been to blame; we noticed some weirdness around it. (There's a chance we'll even remove it at some point, since I don't think Electron even makes it possible to do what we had in mind by adding it.)

My next suggestion would've been that you start in safe mode with `pulsar --safe` — but if `allowWindowTransparency` was the problem, even that wouldn't have fixed it. Glad you arrived at this fix.

> Just to complement this, does anyone know if there is a guide on how to correctly edit what is in the config.cson file?

The format of `config.cson` is inspired by CoffeeScript. [This README](https://github.com/bevry/cson) is a good introduction; it's JSON but without mandatory key quoting (in most cases), mandatory commas, and mandatory delimiters. Like CoffeeScript, indentation is significant.

If you're asking about the settings themselves, that's harder to answer, since it depends on which packages you've got installed. In general, it's not a great idea to edit `config.cson` directly unless you're making a small change. Making changes in the settings GUI will commit new settings to `config.cson` automatically. If you think you've broken your `config.cson`, you can quit Pulsar, rename it (so you still have the old contents), and relaunch Pulsar; a new default `config.cson` will be created.

If you want to be able to revert to older versions of `config.cson` if something like this happens again, [sync-settings](https://web.pulsar-edit.dev/packages/sync-settings) may be useful; it can back up your settings, your styles, your installed packages, and your init script to a GitHub Gist.
