### ISSUE TITLE
Pulsar does not show keybindings table for xml-formatter package

### ISSUE THREAD

**Issue by jmanuel1** [pulsar-edit/pulsar#1160]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

In my installation of Pulsar, when I install the xml-formatter package from the registry or Git, the keybindings table in the setting page for the package doesn't show up. @savetheclocktower tried installing the package from Git and the table showed up for him.

IDK if I can reproduce this in safe-mode because I don't know how to install a package in safe mode. But I can reproduce after moving my .pulsar folder to somewhere else, both with a package registry and Git install.

### Pulsar version

1.123.0

### Which OS does this happen on?

🪟 Windows

### OS details

11

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Install [xml-formatter](https://web.pulsar-edit.dev/packages/xml-formatter)
2. Go to the settings page in Pulsar for the xml-formatter package
3. Observe that the package's keybindings aren't listed by Pulsar on that page?

### Additional Information:

I haven't observed this behavior from any other package

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this issue!

I'm taking a look into this one, and while my current machine is on a slightly older version of Pulsar, I also don't see the keymaps for `xml-formatter`.

I've gone through the source code and testing in my console to confirm that `settings-view` should be able to build the keymap data for this package just fine, since the data is available via `atom.packages.getLoadedPackage("xml-formatter").keymaps` and running `atom.keymaps.build("xml-formatter", atom.packages.getLoadedPackage("xml-formatter").keymaps[0][1], 0, false)` does properly build a valid output of the keymap itself.

So we should be fine there, where I'm theorizing this is failing is during a [platform compatibility check](https://github.com/pulsar-edit/pulsar/blob/master/packages/settings-view/lib/package-keymap-view.js#L131).

Since you are on Windows, and I'm also on Windows, it would make sense this issue may be platform dependent.

Within the `xml-formatter` keymaps we have the following keybindings listed, with the following system compatibility specified within the keymaps themselves:
* `xml-formatter:indent`: `win32, linux`
* `xml-formatter:minify`: `win32, linux`
* `xml-formatter:indent`: `darwin`
* `xml-formatter:minify`: `darwin`

So I'm almost wondering if the platform compatibility check is failing on Windows and Linux because it lists both? Meanwhile, things would be fine on macOS since they have their own items.

The check itself is preformed via regex, where if there's a match the keymap is skipped from being displayed, and this regex checks if there's a platform other than the current platform listed within the selector. Which when on Windows or Linux, there will be a platform listed that is not the current one, because it lists both.

---

Interestingly enough, we can nearly confirm this is what's happening in Pulsar's own `settings-view`!
`settings-view` has the following keymaps:

```cson
'.platform-darwin':
  'cmd-,': 'settings-view:open'

'.platform-win32, .platform-linux':
  'ctrl-,': 'settings-view:open'
```

Notice here that we have one layout for macOS users, then another layout that includes both Windows and Linux users.
If my theory is correct on the cause of this issue, then we won't see any keymaps for the `settings-view` package either, which if I check my `settings-view` page in settings:

![image](https://github.com/user-attachments/assets/5782c179-f45e-4402-92be-f6bbb21f1db9)

We also don't have any keymaps listed there. So it does seem this is the root cause of the problem.

As for how to fix it, I'm not totally sure. We could either make the platform compatibility check more advanced, or we could list all keymaps, then indicate that some of them don't seem to be for this platform. So that way even if the platform check here is wrong, users can still view all keymaps and try them anyway. But would be happy to hear any other ideas, and for anyone that wants to think of ways to fix the [compatibility check](https://github.com/pulsar-edit/pulsar/blob/master/packages/settings-view/lib/package-keymap-view.js#L14) here's what it looks like:

```js
this.otherPlatformPattern = new RegExp(`\\.platform-(?!${_.escapeRegExp(process.platform)}\\b)`)

...

if (this.otherPlatformPattern.test(selector)) {
  continue
}
```
