### ISSUE TITLE
GitHub Copilot Integration

### ISSUE THREAD

**Issue by SilentGlasses** [pulsar-edit/pulsar#1170]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

No Screenshots needed, would like to ask for integration for GitHub Copilot integration.

### What benefits does this feature provide?

Ability to use GitHub Copilot features to aide with tasks and general work.

### Any alternatives?

Currently, none that I know of.

### Other examples:

Currently works in Visual Studio Code 

https://marketplace.visualstudio.com/items?itemName=GitHub.copilot

**Comment by confused-Techie** [comment]
Thanks a ton for contributing!

This is actually something we already have an open and existing issue for over on #792. 

As such I'll be closing this issue to keep down on duplicates.

But because you took the time to create the issue, I'll go ahead and provide a tldr on where our discussion last left off.

Essentially, while it's a great idea, I did mention that as anyone can create and publish a package for Pulsar, we'd encourage anyone to take a shot at this, with several users announcing their efforts in this arena. 

Our major concern with attempting to officially support something like this really comes down to the lack of an official API that we can rely on for GitHub Copilot, and other similar tools like Codium. Without an official API we would have to spend serious time reverse-engineering say the VSCode extension, and if that API ever changes, then we'd have to do it all over again.

So once we can find a solid model out there with an official API that we can rely on to write once and not have to baby-sit it, then I'd be a lot more open to the idea.

But if you've got further ideas or points I'd love to hear your thoughts over on the original #792 issue!
