### ISSUE TITLE
We need a way to update packages

### ISSUE THREAD

**Issue by benonymus** [pulsar-edit/pulsar#133]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Once package installation works form the new backend we will need a way to update said packages.
atom-elixir-formatter for example gives an error and does not work on Pulsar until a small fix is made.

We cannot expect the original maintainers for every package to update their packages in case that is necessary.

### Enter your response below:

Reliable packages

### Any alternatives?

We could go out of our way to be more backward compatible, but considering the numerous third party dependencies this might be very difficult.

**Comment by confused-Techie** [comment]
Are you aware of what the small fix is? I'd assume that Pulsar checks with the backend for new updates? Rather than checking the package itself?

**Comment by benonymus** [comment]
Yes I am. I have it fixed locally. I am not sure what you mean by the other part of the comment.

**Comment by confused-Techie** [comment]
> Yes I am. I have it fixed locally. I am not sure what you mean by the other part of the comment.

What I mean, is if we want to update a 3rd party package that is installed, I would assume that Pulsar checks the backend to see if a new version of this published package is there, and if so download it.

Or are you not talking about a new version of a package? 

Since if you are referring to an update is needed for packages to work at all, we are hoping that isn't the case. Since ideally most if not all packages will still be compatible with Pulsar

**Comment by Daeraxa** [comment]
What exactly is the fix. If we know what the fix is then it can be looked into to see if it was something we changed in Pulsar or if an Atom version broke something which may have broken other community packages.
If it was something we broke in Pulsar then we could look at seeing if that break is necessary or an accident etc.

**Comment by benonymus** [comment]
Ah, a fix is needed to work on Pulsar yes.

**Comment by Daeraxa** [comment]
And what is it?

**Comment by benonymus** [comment]
On this line: https://github.com/rgreenjr/atom-elixir-formatter/blob/master/lib/formatter.js#L57
the `projectPath` variable is passed in the call before it is being declared. It is no needed so it can be safely removed.
In atom this did not cause any issues, in Pulsar it stops the formatter from working.

**Comment by confused-Techie** [comment]
Interesting, I can absolutely see why it would cause our formatter to stop working, because it is a syntax error. Although I wonder what change causes this to fail now? Are you aware of a version when this stopped working? Or just that it doesn't work currently?

**Comment by benonymus** [comment]
It hasn’t worked for a while. I think maybe even since I gave pulsar a go about 2 months ago, maybe more.
I haven’t tried the published version for a long time, I use my fixed variant.

Bence Janos Toth
________________________________

**Comment by confused-Techie** [comment]
Thanks for letting me know. If its been broken that long it may be related to one of the Node or Electron bumps, so those were some of the first things changed after basic rebranding and such. But still interesting. If related to a bump there may be only so much we can do, but I'd be interested if anyone has an older version of Pulsar that can be tested

**Comment by benonymus** [comment]
Yeah those are my guesses as well for cause.

Bence Janos Toth
________________________________

**Comment by confused-Techie** [comment]
Since there's nothing that can be done on Pulsar's end to fix this issue, as it ultimately stems from this package being written in JavaScript Sloppy Mode, I'll apply the appropriate badging to this package, and close this issue here. Thanks a ton for reporting this issue, and if you'd like to follow up with the badging applied to this package, feel free to look [here](https://github.com/pulsar-edit/package-backend/issues/158).

**Comment by Daeraxa** [comment]
If the original user is not responding and is unwilling to modify it then the easiest way is to make a fork and publish it yourself.

**Comment by confused-Techie** [comment]
Which @benonymus if you do decide to publish a fork of this package please let us know! There's been some talk about prompting users to install more up to date packages instead of those that are known to be broken. Like in this case
