### ISSUE TITLE
Dev tools don't open without `--no-sandbox`

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/pulsar#199]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

This happened after I upgraded my OS from Linux Mint 20.3 to 21 (Ubuntu 20.04 -> 22.04). However it *also* happened after a smaller system update on Fedora 36.

The dev tools no longer work unless Pulsar is launched with `--no-sandbox`. The application itself launches normally but any attempts to open the tools fail (`Window: Toggle Dev Tools`, ctrl+shift+i, view > developer > toggle developer tools). No errors created, no logging to the terminal.

Launching with `--no-sandbox` causes them to work again ([resolution](https://discord.com/channels/992103415163396136/992103415163396139/1049547459795370094) from @DeeDeeG).

Ideally Pulsar should be able to open the dev tools regardless of whether `--in-process-gpu` or `--no-sandbox` is used. It should certainly throw an error if it is unable to open the dev tools for whatever reason.

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Linux Mint 21 (but also on Fedora 36)

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Launch Pulsar with no additional parameters from dev, appimage or tar.gz binary.
2. Attempt to open dev tools

### Additional Information:

Built from 3646a714c

**Comment by DeeDeeG** [comment]
Context: The part where these flags are needed at all is a known issue, happening on any recent Linux distro and Electron versions less than 13.x latest.

Details: https://github.com/atom/atom/issues/23036#issuecomment-939500928 

Best solutions would be:
- Get on Electron 13+
- Or as a workaround, do one of the the `--in-process-gpu` or `--no-sandbox` flags.

Due to your pointing it out and folks testing both flags to compare, what's new since that original issue was posted, is that we now know `--in-process-gpu` breaks the Dev Tools.
