### ISSUE TITLE
Document or prevent settings-view package being disabled

### ISSUE THREAD

**Issue by ljsinclair** [pulsar-edit/pulsar#203]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

I made a mistake earlier and disabled "settings-view".
At the time it seemed the only way to get it back was to perform a clean install.
Then I found I could enable it by removing the disabled package from the list in config.cson

I did a search for "enable package" in on the pulsar website, but nothing came up.
On the other hand, search on "package" gave me results related to maintaining packages that was very long on screen and didn't scroll.

So there are two fixes for this:

1. don't allow "settings-view" to be disabled in the first place as this is ultimately core functionality (IMO)
2. document what to do if a package is disabled.

For example:

---

title: Enable and disable packages in Pulsar Edit

This page explains how to enable and disable packages via the settings page or in the config.cson settings file.

## Enable and disable packages via the settings page

1. Click **Packages** > **Open Package Manger**
2. Search for the package.
3. Click Enable or Disable as required.

## Enable packages via config.cson

1. Click **File** > **Config**
2. Scroll to find `disabledPackages`.
3. Select the package with surrounding quotes and delete.
4. Click **File** > **Save**.

## Disable packages via config.cson
1. Click **File** > **Config**
2. Add `disabledPackages` if it does not already exist:
```
disabledPackages: [

    ]
```
3. Add your package-to-disable within the square brackets, for example:

```
disabledPackages: [
      "package-name-to-disable"
    ]
```

**Comment by confused-Techie** [comment]
I think no matter what we do here having a document about how to interact with the Config file in this way is a good idea. Maybe we could have a Usage Example Document that can highlight different examples like this and how to use them?

But on the subject of disallowing the settings-view package to be disabled, while you are correct that we intend for it to be a Core Feature, and always required, personally I feel we can't know every use case, and someone out there may want it disabled, and I don't think we should be the one to stop them. Placing limitations seems contrary to the "Hackable" nature of Pulsar. 

But that's just my two cents. I know our site docs aren't finished, so this may be in the works.

But otherwise thanks for pointing out this oversight in functionality

**Comment by ljsinclair** [comment]
One other thing to consider is that disabling "settings-view" does not disable "Packages > Open Package Manager".
This means the user can click the menu item as much as they like, but nothing is going to appear. This could then be reported as a bug because it's non-obvious that this has been caused by disabling "settings-view".
Can I suggest therefore that:
* If settings-view is disabled
* The system displays a tab when "Open Package Manager" is clicked
* The tab displays something like "Enable this view by opening File > Config then delete "Settings-View" from `disabledPackages` then save.

**Comment by Sertonix** [comment]
I would say the "Open Package Manager" menu should be removed if the settings view package is not activated.
And there should be a note on how to enable/disable packages without the settings-view in the packages documentation.

**Comment by confused-Techie** [comment]
@ljsinclair Good point, I didn't realize that this could result in that behavior. In that case yeah I'd be on board with having the menu items disappear, or have them change to say enable or a notification. Or anything to clearly communicate to the end user what's happening and why.

**Comment by ljsinclair** [comment]
My vote is to leave the Open Package Manager menu item where it is and provide guidance in the UI on how to restore the functionality (as suggested above)
It's non-obvious that disabling settings-view will even affect the packages view. And this means if the package is disabled, the user will have to guess what to look for in help.

**Comment by Sertonix** [comment]
The only concern I have is that we add a lot of help code to the core and it gets bloated. Other then that I would be fine with a help notification.

**Comment by ljsinclair** [comment]
Totally hear you @Sertonix on not wanting bloated code and perhaps there should be some kind of guidance put together to prevent this happening?

Doing a [Doctor Who and reversing the polarity](https://www.youtube.com/watch?v=QDaCMhKPGys) for a moment, how about adding a warning that will pop up and let users know when disabling certain functionality will break things?

We've established the need for the enable/disable packages already of course, and this page can be improved by adding information such as:

> The core [settings-view](URL to package page) package allows you to add, update, change settings and delete packages via the  Packages menu. If disabled, you can add and disable packages [via the config.json file](BOOKMARK LINK TO Enable packages via config.cson)

**Comment by Sertonix** [comment]
A warning when disabling is a good Idea! The code that does this could also be included in the settings-view package. Maybe the message can link to the documentation where a detailed explanation is.

**Comment by preland** [comment]
I actually was going to say something about this, because I ran into this as well (although admittedly, I was trying to see if Pulsar would break when every core package was disabled [it didn’t btw]).

While a warning would be nice, I think that it would also be good to have a ”default” page for settings if the package doesn’t load (or if the package were to become damaged in the future 😬). 

The only reason I say this is because disabling settings-view (at least in my case) caused some significant visual and UI artifacts, which could cause some confusion in the future.

I’m just throwing out ideas though. I don’t know if it’s even possible to have a default page (though disabling the about and welcome pages does just open a blank file).

**Comment by Sertonix** [comment]
I would say that the config file is the default page settings. So no need for another page.

**Comment by ljsinclair** [comment]
@Sertonix > sorry for delay responding.
The config file is the page settings, **but** it's accessible via the File menu (at least on Windows), so it's non-obvious this will contain the settings to get the settings-view back and to manage the packages, etc.

So an alternate view is:

* WHEN settings-view is disabled
* AND user clicks  **Package Manger**
* THEN PROTON opens a new tabl with config.cson file (the same as if they opened File > Config...)

**Comment by Daeraxa** [comment]
Could you confirm the behaviour is still the same now settings-view has been incorporated into the core? I don't think it would be any different but no harm in checking.

**Comment by Sertonix** [comment]
I know this is not really what people wanted but #243 would be the way I like.

**Comment by Sertonix** [comment]
> Could you confirm the behaviour is still the same now settings-view has been incorporated into the core? I don't think it would be any different but no harm in checking.

It is the same. Everything else would be very weird.
