### ISSUE TITLE
I hope pulsar to use a new interface of its own

### ISSUE THREAD

**Issue by Ark2011-s** [pulsar-edit/pulsar#259]
### Have you checked for existing feature requests?

- [x] Completed

### Summary

I HOPE pulsar to use a new interface of its own

### What benefits does this feature provide?

This makes the editor look BRAND NEW!

### Any alternatives?

no

**Comment by Ark2011-s** [comment]
If pulsar continue to use the Atom theme (not ui), this will look very corny. All I want is an editor that is compatible with the atom package(I don't speak a lot of English, so use a translation tool)

**Comment by Ark2011-s** [comment]
and, I would like to change the Pulsar logo

**Comment by Digitalone1** [comment]
> and, I hope development team change the Pulsar logo, too.it is VERY ugly!

I don't think so. We made a vote for it. The selection has been already done.

**Comment by confused-Techie** [comment]
While I appreciate you contributing @Ark2011-s because the Icon is something that we as a collective community voted on I don't see it being changed anytime soon.

Unless there was specific feedback about how to improve the icon or our branding, I'm not sure how much we can do with "it is VERY ugly".

If anyone else on the team disagrees feel free to reopen this but as there's no actionable content here, I'll go ahead and close this one.
