### ISSUE TITLE
Windows: Bad install folder and forced

### ISSUE THREAD

**Issue by Neustradamus** [pulsar-edit/pulsar#277]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The "Windows.Pulsar.Setup.1.100.0-beta.exe" installer forces install of the product in:
C:\Users\USERNAME\AppData\Local\Programs\pulsar\

There is no question where it must be installed and by default, it must be, if it is a:
- x64 build: C:\Program Files\Pulsar
- x86 build: C:\Program Files (x86)\Pulsar

Thanks in advance.

### Which OS does this happen on?

🪟 Windows

### OS details

ALL

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

Launch "Windows.Pulsar.Setup.1.100.0-beta.exe" and look the C:\Users\USERNAME\AppData\Local\Programs\pulsar\ folder.

**Comment by confused-Techie** [comment]
So I do totally agree that Users should be given a choice of install location, although one thing to note here, is if we move the default location outside of AppData that'll break user only installs.

That is anyone attempting to install Pulsar onto an Enterprise managed PC will no longer be able to install without IT or Admin assistance, and could possible affect those using a shared system as well, to where this will install the application globally for all users on a system, and if said user is not the administrator of the system will again be unable to install at all.

Additionally I'm pretty sure Atom's default install location was into the AppData folder as well, but I may be wrong on that one.

@Neustradamus is there a reason we need to make this change? Did it negatively affect anything on your system?

**Comment by Neustradamus** [comment]
@confused-Techie: To install a new version, it removes the previous, there is not break ^^

People want to select the installation folder on Windows OS instead of the %LocalAppData% forced.

Microsoft Windows uses since a very long time:
- "Program Files" on 32-bit or 64-bit OS: %ProgramFiles%
- "Program Files (x86)" for 32-bit applications on 64-bit OS: %ProgramFiles(x86)%

Of course, people must to select another folder too.

A lot of server admins and users have space problem on a machine.

And with deployment of roaming user profiles :
- Data multiplication by users on machines
- Data multiplication by users on servers
- Data multiplication by users on local backups
- Data multiplication by users on external backups
...

**Comment by confused-Techie** [comment]
@Neustradamus As a Windows Admin for a small org myself I'm familiar with the general layout of applications, but installing an app into AppData isn't in of itself a bad thing. And in general is a common choice from some applications.

And again I'm on board with finding out how we can present this option to the user, but installing our application here alone I wouldn't think would lead to space problems? Unless there's something I'm missing.

If anything the application being installed into AppData could help ensure the data is associated to the user account and backed up in some backup methods.

But otherwise was just wanting to see if there was an exact reason you labeled the issue as "Bad install folder" since really it's just a choice of the three major install locations (Four if we include the Windows Store Installation Directory), rather than a feature request to change the default.

And for anyone not on a Windows System to know the discussion here, the AppData folder is a common default location for App installs, such as NVIDIA, Firefox, Atom, Bitwarden, Discord, Docker Desktop, Electron, GitHub CLI, GitHub Desktop, Golang, Google Chrome, Firefox, Steam, Teams, `node-gyp`, `pnpm`, `yarn` and so on, so it isn't the wrong place to install an app as clarification.

**Comment by Neustradamus** [comment]
About forced %LOCALAPPDATA%, several softwares have a problem because Squirrel based!

GitHub Atom, GitHub Desktop and other softwares have tickets about this problem...

Mozilla Firefox permits to select and by default it is "%PROGRAMFILES%".
Google Chrome has "Enterprise" build which permits too: https://chrome.com/enterprise.
Nvidia drivers is installed in "%PROGRAMFILES%".


More informations about folder in Microsoft Windows:

1/ %PROGRAMFILES% is a folder first found in Microsoft Windows 95 and included in all later versions of Microsoft Windows that stores the software programs installed on the computer.

2/ %USERNAME%\AppData
- Local: This folder stores device-specific settings and temporary files. There is a separate %LOCALAPPDATA% environment variable for this folder that you can use in your batch files and scripts.
- LocalLow: Here, Windows mainly stores buffer data generated by various applications (Internet Explorer, Java, Adobe, etc.). It is also used by low-level access systems, for example, for your browser's temporary files when working in Protected View. This directory also cannot be moved to another computer.
- Roaming: You can transfer files from this folder to another computer. The Roaming folder stores browser data, bookmarks, etc. This directory allows users to always work with a familiar environment on any server in the Remote Desktop Services farm when using roaming profiles or user profile disks. The environment variable for this directory is %APPDATA%.
