### ISSUE TITLE
Install package fail

### ISSUE THREAD

**Issue by Flashwalker** [pulsar-edit/pulsar#348]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Install package fails:

`API returned: `
```json
{"message":"Too many requests, please try again later."}

```

### Pulsar version

1.101.0-beta

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

22.04

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Try to install package

**Comment by Daeraxa** [comment]
You have simply hit the limiter we have in place on the backend to stop it getting flooded. It should reset shortly so you can access it again.

**Comment by Flashwalker** [comment]
> You have simply hit the limiter we have in place on the backend to stop it getting flooded. It should reset shortly so you can access it again.

It looks like it triggers almost with each character i typing in a search.
The limit is reached after installing or searching for one or two packages.

**Comment by Daeraxa** [comment]
The 1.101.0 beta should have a search delay implemented by https://github.com/pulsar-edit/pulsar/pull/289. If it is a problem you could search on the package repo directly at `web.pulsar-edit.dev` then install the one you need with `pulsar -p` as that wouldn't create any extra traffic.

**Comment by Flashwalker** [comment]
ok, thanks

**Comment by machitgarha** [comment]
In the latest stable (1.102.0), the problem persists. No matter what command I enter, e.g. `search` or `install`, it gives me the too many requests error.

**Comment by Spiker985** [comment]
The rate limiting is currently set up for an interval of 15 minutes, I believe.

When Pulsar starts, it checks for updates. Since there are 80+ Core packages - even without community packages - you use up some available requests. Subsequent navigations to `Settings -> Updates` checks again. So does closing/reopening the editor.

We intend on making changes (since GitHub never had a rate limit in place previously) so we can cache responses so this doesn't happen as frequently.

However, for your particular situation, simply open the Settings -> Install section, and wait approximately 15 minutes and you should be fine.

Everyone is a bit different because of the number of packages installed, but generally that should reduce the number of times you get the message

You can also browse for packages on https://web.pulsar-edit.dev if you so desire

**Comment by icecream17** [comment]
it might be more efficient to batch requests together, i.e. checking whether any of 80 packages needs to be updated is one request

**Comment by bobemoe** [comment]
Maybe we need to re-open this? I Just hit the same issue, can barely search for and install one package before hitting the limit. Clean install, just trying to install my 2 usual packages (tabnine, build) so not many beyond core.

Some useful workarounds above, thanks, so no big issue really but doesn't gave a smooth experience!

**Comment by bobemoe** [comment]
Also, as @Flashwalker above said, "It looks like it triggers almost with each character i typing in a search." maybe disabling this real time results could save a load of requests?

**Comment by confused-Techie** [comment]
@bobemoe Are you on the latest version?

Pretty sure we did disable the real time searching a couple versions ago.

Also like mentioned above, we do rate limit the requests because we do have to pay for each request. 
But the rate limit is raised as needed, currently we have the rate limit set to 600 requests per 15 minutes per IP (For none authentication requiring endpoints). So it seems very very odd you'd hit that limit by searching and installing only 2 packages. 

If you're willing I'd be interested to talk further with you to try and see how that could've happened. Are you on our Discord server?

**Comment by confused-Techie** [comment]
So to add to this, I've taken this chance to deep dive in our logs.

I think I was able to successfully find you're string of queries by checking for a hit for `tabnine` against requests that `429`ed (Hit the RateLimit).

Indeed it weirdly seems that after only 70 or so requests the RateLimit kicked in. 

So I took a further look at this. And this is embarrassing to say, the RateLimit seems to have been modified, since I last set it.

Using Git Blame, it looks like at one point a PR towards the repo had reverted a commit to the backend that ended up reverting the change that increased the RateLimit to 600.

Take a look at PR [`pulsar-edit/package-backend#16`](https://github.com/pulsar-edit/package-backend/pull/16).
Specifically [this](https://github.com/pulsar-edit/package-backend/pull/16/commits/10b9490b48c33dd45a66bf392f084a2971e27350) commit had reverted these changes. 

But since that change never actually showed up in the final [diff](https://github.com/pulsar-edit/package-backend/pull/16/files) this regression was missed.

So in that case incorrectly the rate limit is placed at 75 requests per IP per 15 minute window. And explains why we keep getting reports of the RateLimit being hit even after continually increasing it.

So apologies to those experiencing the issue, I'll go ahead and revert this as soon as I can.

**Comment by confused-Techie** [comment]
FYI, I've pushed [`pulsar-edit/package-backend#93`](https://github.com/pulsar-edit/package-backend/pull/93) which fixes the regression on RateLimiting.

So now truly the RateLimit is set to 600. So hopefully we won't continue to see this issue effecting normal users.
