### ISSUE TITLE
Cannot install minimap package requiring native functionality/integration/code

### ISSUE THREAD

**Issue by Pysis868** [pulsar-edit/pulsar#411]
- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

> Installing “minimap@4.40.1” failed.
> 
> npm ERR! code ERR_SSL_WRONG_VERSION_NUMBER
> npm ERR! errno ERR_SSL_WRONG_VERSION_NUMBER
> npm ERR! request to https://registry.npmjs.org/atom-utils-plus/-/atom-utils-plus-0.11.0.tgz failed, reason: 25988:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:308:
> npm ERR! 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\<username>\.pulsar\.apm\_logs\2023-03-02T18_19_33_412Z-debug.log

Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Please install Python and Visual Studio to continue.
Run pulsar -p install --check after installing to test compiling a native module.
```
> pulsar -p install --check

Checking for native build tools failed
> module-with-native-code@ install ...\Pulsar\resources\app\ppm\native-module
> node-gyp rebuild


...\Pulsar\resources\app\ppm\native-module>if not defined npm_config_node_gyp (node "...\Pulsar\resources\app\ppm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "...\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

npm WARN lifecycle The node binary used for scripts is ...\nodejs\node.exe but npm is using ...\Pulsar\resources\app\ppm\bin\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to usegyp ERR! stack     at VisualStudioFinder.fail (...\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at ...\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (...\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at ...\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at ...\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at ...\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at ...\Pulsar\resources\app\ppm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:326:5)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "...\\nodejs\\node.exe" "...\\Pulsar\\resources\\app\\ppm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ...\Pulsar\resources\app\ppm\native-module
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! module-with-native-code@ install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the module-with-native-code@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\.pulsar\.apm\_logs\2023-03-02T18_48_44_317Z-debug.log
```

### Pulsar version

1.102.0

### Which OS does this happen on?

🪟 Windows

### OS details

10 Pro x64 Version 21H2 Build 19044.1889, cygwin 3.3.5-341.x86_64

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1.
   - GUI install minimap package
   - or, CLI install check: `pulsar -p install --check`
2. `set -x VCINSTALLDIR (gc)`, then step 1 CLI again, exhibits the same problem.

### Additional Information:

Debugging guide seems not relevant.
- https://github.com/issues?q=user%3Apulsar-edit+%22Microsoft+Visual+Studio%22+%22unknown+version%22
- https://github.com/issues?q=user%3Apulsar-edit+%22ERR_SSL_WRONG_VERSION_NUMBER%22+
> Version 1.102.0 is the latest version.
```
> ls 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community'
 Common7/       dotnet/           Licenses/  'Team Tools'/   VC/    Xml/
 DesignTools/   ImportProjects/   Msbuild/    TS/            VC#/
'DIA SDK'/      JS/               SDK/        VB/            Web/

> ls '/cygdrive/c/Program Files/Microsoft Visual Studio/2022/Community'
 Common7/       dotnet/           Licenses/  'Team Tools'/   VC/    Xml/
 DesignTools/   ImportProjects/   Msbuild/    TS/            VC#/
'DIA SDK'/      JS/               SDK/        VB/            Web/

> cygcheck -c cygwin
Cygwin Package Information
Package              Version        Status
cygwin               3.3.5-1        OK

> uname -r
3.3.5-341.x86_64
```

A restart of the application, or merely a re-install/-download of the minimap package seems to have succeeded now,
although the check process still seems flawed, to still be improved, and have these keywords exist in the issue for others to find.
Also could the SSL error be explained?  Entirely random?  I have no network proxies.

**Comment by confused-Techie** [comment]
So just going to mention real quick, we have had issues with the bundled NPM within PPM have trouble finding newer versions of Visual Studio because it's quite old. Haven't had a chance to read all the details, but did want to mention that further bumps to PPM would help that portion of the issue.

But thanks for the report!

**Comment by Spiker985** [comment]
Visual Studio 2019 is the most recent version that I've found to work. 2022 isn't a valid version in ppm's npm

**Comment by Pysis868** [comment]
Is there a link to something tracking that issue more specifically?

**Comment by confused-Techie** [comment]
> Is there a link to something tracking that issue more specifically?

No there is not. Essentially it comes down to our core goals of updating everything. Once we can get the bundled NPM of PPM updated this issue goes away. So it's less an issue and more a compatibility concern. 

Really I'd think they best way to be made aware of it is changelogs, of seeing that NPM has been bumped. Which I'm pretty sure every release since `1.101.0` has included a small NPM bump, so it is something being actively worked on.

Although it may be on one of our project boards

**Comment by goyalyashpal** [comment]
![image](https://user-images.githubusercontent.com/19423063/230990766-2bfedbf2-8d75-4243-9c35-e16c3da31d7b.png)


```
Installing “uber-juno@0.3.0” failed. Hide output…
/usr/bin/bash: /s: No such file or directory
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Please install Python and Visual Studio to continue.
Run pulsar -p install --check after installing to test compiling a native module.
```

Pulsar Version: 1.103.0
OS: Win 10 22h2 (with msys2)

Try installing [Ubser Juno](https://web.pulsar-edit.dev/packages/uber-juno) (after associating Pulsar as "default `atom://` protocol handler" under URI Handling.

Also, This error or `/usr/bin/bash: /s: No such file or directory` is shown in most all places in settings in pulsar.

**Comment by confused-Techie** [comment]
@goyalyashpal the issue you are describing here is totally different then where you've made this comment.

It'd really likely make the most sense to create your own issue for this.

But just to try and get it resolved quickly, keep in mind the error you are seeing is saying directly that the package you are attempting to install requires native modules. Meaning you need to have a C++ build toolkit installed, this means installing Python, and Visual Studio.

* Visual Studio Community 2019 is the most recent version that will work with our outdated NPM
* Python `3.10` is the correct version of Python to be using with Pulsar.

Otherwise the error `/usr/bin/bash: /s: No such file or directory` seems very telling as that's an error I haven't seen before.

So then the question becomes how did you install Pulsar? Was it from our Website?

**Comment by goyalyashpal** [comment]
> So then the question becomes how did you install Pulsar? Was it from our Website?

have opened up the dedicated issue linked above: 482

**Comment by Pysis868** [comment]
Keeping the current, modern version since I use it for other projects too.

**Comment by confused-Techie** [comment]
@Pysis868 Yeah keeping the up to date version is fine. But it won't be detected just yet with Pulsar. But installing the older version side by side shouldn't cause any issues

**Comment by confused-Techie** [comment]
@Pysis868 So we have been able to update `node-gyp` within PPM, to a version that does have support for Visual Studio 2022! 

Feel free to read into the details over on [the pr](https://github.com/pulsar-edit/ppm/pull/79). Keep in mind these changes will not appear within Pulsar until our PPM is updated, which may happen around 1.109.0, since 1.108.0 already has a possibly breaking PPM change within it (and we like to stagger those if possible). So it'll take some time, but I'll try to keep this issue in mind once we bring those changes into Pulsar itself.

**Comment by savetheclocktower** [comment]
@confused-Techie did this end up in 1.108 after all?

**Comment by confused-Techie** [comment]
@savetheclocktower Thanks for following up. But no, this is not in 1.108.0, but we should make sure to include it within 1.109.0

Since we had the binary renames in this one, the PPM repo had wanted to minimize churn per release to as little as possible.

**Comment by confused-Techie** [comment]
@Pysis868 I know this issue is older, did just want to call out if you weren't aware, the related updates are now fully within Pulsar.
I'd recommend installing Pulsar v1.110.0 to be able to use the latest Visual Studio 2022, and Python 3.11 to build native modules as needed. And as long as things work there we should be able to close this one out.

Thanks for your patience!
