### ISSUE TITLE
Inconsistent theme on the top bar

### ISSUE THREAD

**Issue by cat-master21** [pulsar-edit/pulsar#422]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

On GNU Linux (KDE and Gnome) the top bar 
![image](https://user-images.githubusercontent.com/96554164/224519151-4c5f0960-385b-4813-89eb-0f485d46e817.png)
does not change making it inconsistent.

### Pulsar version

102.0

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 37

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Change the system theme to dark mode
2. Change the Pulsar theme to any, can more easily be seen on dark mode.
3. Notice that the top bar doesn't change

### Additional Information:

![image](https://user-images.githubusercontent.com/96554164/224519104-16ec6d61-7deb-43dd-bc35-257b99055cd9.png)
![image](https://user-images.githubusercontent.com/96554164/224519119-22b0d3d4-dc93-45d6-a5be-75657edd6fe5.png)

**Comment by icecream17** [comment]
hmm, looks like there's no system to change theme automatically when the system theme changes.

does pulsar expose window properties like that to packages?

**Comment by Daeraxa** [comment]
This is the same in Atom, the menu bar is native to the OS so in theory should only change according to the OS theme, not Pulsar's (I've seen this before in Electron apps).

One way to resolve this eventually would be to move to a non-native menu bar which I detailed here - https://github.com/pulsar-edit/pulsar/issues/345 as it would be fully under Pulsar's control no matter what the OS is.

**Comment by icecream17** [comment]
I feel like electron must have a solution...
ideally a package (or core) could detect when the system theme changes, and change pulsar's theme accordingly

**Comment by Daeraxa** [comment]
https://www.electronjs.org/docs/latest/tutorial/dark-mode

Looks like it is possible here?

**Comment by confused-Techie** [comment]
I'm pretty sure that would mean we have to bump electron a bit before that could be done. But might be wrong

**Comment by confused-Techie** [comment]
Actually @Daeraxa I think you are right. We should be able to use this and can likely expose it as an additional Pulsar API for theme makers to take advantage of. Probably recommending they put it in the `activate()` (or equivalent call).

Looks like it was added in [Electron V7.0.0-beta6](https://releases.electronjs.org/release/v7.0.0-beta.6), so I'd imagine it's available in v12.2.3 which is what we are currently using.

**Comment by confused-Techie** [comment]
So I was looking into how we might be able to accomplish this.
Since obviously exposing an API to style the window theme is great, it wouldn't solve the problem of the hundreds of themes that already exist, not then being able to take advantage of this without updates.

So I'm considering, what if we don't prioritize an API to do this, but rather, we focus on making Pulsar do it automatically. I'm considering within the `theme-manager` what if, once the theme has changed, we could use something like `getComputedStyle(documentElement).backgroundColor` which will return an RGB value for the app's background color, (this is the color used behind tree-view, and the top menu) and then we could essentially calculate the brightness of this color, and if calculated to be brighter, then we could automatically make the window theme light, or otherwise make the window theme dark.

I feel like this might be a pretty elegant solution.

**Comment by confused-Techie** [comment]
So playing around with this method, I do have the `theme-manager` accurately determining when the theme is lighter or darker, as well as I have Pulsar accurately setting `nativeTheme.themeSource` to whatever is needed, but I think I've now hit an Electron issue.

The testing below is on Windows, and based on [this discussion](https://github.com/electron/electron/issues/23479) may be a Windows only problem, but I'll continue anyway:

### When set to a light theme with my changes:
![image](https://github.com/pulsar-edit/pulsar/assets/26921489/93d065e4-4da7-4c04-9cc5-e5893e3b9d4c)

### When set to dark theme with my changes:
![image](https://github.com/pulsar-edit/pulsar/assets/26921489/8e19a051-407f-4f2f-be2a-1e89a3265cfc)

So as you can see when compared to previous behavior, like below:
![image](https://github.com/pulsar-edit/pulsar/assets/26921489/4ddfd061-5def-48c7-9d10-7537b405839b)

This is absolutely an improvement, and I'm curious if this behavior will exist on other platforms. Which if on other platforms the top menu bar of Electron apps already respect Dark mode, I assume it will. (Since even the Pulsar menu bar with the title doesn't respect my OS level Dark Mode on Windows)

**Comment by cat-master21** [comment]
So after looking at the Pulsar Flatpak, setting the `GTK_THEME` to `Adwaita-dark` in Flatseal set the top bar to black:
![top bar is dark](https://github.com/pulsar-edit/pulsar/assets/96554164/12d1cfd6-1ddf-4526-ac09-585392b60bd2)

**Comment by NeetYunYun** [comment]
If your are using Gnome as wm, you can control top bar theme in Tweaks -> Appearance by switching Legacy Applications' theme.
