### ISSUE TITLE
Faster

### ISSUE THREAD

**Issue by Ark2011-s** [pulsar-edit/pulsar#423]
### Have you checked for existing feature requests?

- [x] Completed

### Summary

pulsar is extremely slow like atom.
i think there is room for improvement

### What benefits does this feature provide?

This will solve the problem of atom editor

### Any alternatives?

No.

**Comment by confused-Techie** [comment]
While we appreciate anyone contributing by creating issues or communicating with us, we are going to need clarification here. 

There's nothing actionable in this issue, nothing exactly that can be worked to improve. We are absolutely wanting to improve performance, but with the amount of work left by the abandoned state of Atom, functionality will have to come first.

Is there any specific instance where you see Pulsar is slow? Opening the editor, opening a file, editing a file, typing, installing?

Because believe me if we could just make it faster we would, but making it faster currently looks like bumping Electron, which means completely rewriting the handful of Native Modules, which means learning C++/C then rewriting several codebases from scratch. Which all of that is in the process and nearly done because we have amazing devs on our team. But it isn't this simple.

**Comment by Ark2011-s** [comment]
> 

and,pulsar is really slow:(

**Comment by Ark2011-s** [comment]
> While we appreciate anyone contributing by creating issues or communicating with us, we are going to need clarification here.
> 
> There's nothing actionable in this issue, nothing exactly that can be worked to improve. We are absolutely wanting to improve performance, but with the amount of work left by the abandoned state of Atom, functionality will have to come first.
> 
> Is there any specific instance where you see Pulsar is slow? Opening the editor, opening a file, editing a file, typing, installing?
> 
> Because believe me if we could just make it faster we would, but making it faster currently looks like bumping Electron, which means completely rewriting the handful of Native Modules, which means learning C++/C then rewriting several codebases from scratch. Which all of that is in the process and nearly done because we have amazing devs on our team. But it isn't this simple.

You can feel how slow it is when it startup
This is still speed without any package

**Comment by Ark2011-s** [comment]
And thank you all devs

**Comment by confused-Techie** [comment]
Okay so it's slow for you when launching. A quick thing to check, are you using the Windows Portable? That one takes quite some time to launch, but otherwise the other versions are what we would currently expect.

**Comment by Ark2011-s** [comment]
> 好的，启动时对您来说很慢。快速检查一下，您使用的是 Windows 便携版吗？那个版本需要相当长的时间才能启动，但除此之外，其他版本就是我们目前所期望的。

No

**Comment by confused-Techie** [comment]
Just thought it was a good idea to check. Thanks for confirming

**Comment by Ark2011-s** [comment]
No,The version I installed using the `Windows.Setup.1.102.0.exe`

**Comment by mrquokka** [comment]
Disagree, pulsar with open big project and load extenstions => 3 seconds, with sata ssd. You can try others IDE, like VSCode, PyCharm, Sublime and wait 7-20 seconds

**Comment by Ark2011-s** [comment]
> 不同意，脉冲星与开放的大项目和负载扩展=> 3秒，与sata ssd。您可以尝试其他IDE，如VSCode，PyCharm，Sublime并等待7-20秒

In fact, Sublime is fast...

**Comment by Ark2011-s** [comment]
Also, is it necessary to close this issue?

**Comment by Daeraxa** [comment]
> I think for an editor, performance has to come first

But that is always going to be a tradeoff. If you want speed then you go for Sublime, Lapce, Zed etc. but if you want the ability to extend, hack or otherwise mess with your editor then you are going to lose some of that performance.

**Comment by Ark2011-s** [comment]
> > 我认为对于编辑来说，性能必须放在第一位
> 
> 但这总是需要权衡取舍。如果你想要速度，那么你会选择Sublime，Lapce，Zed等。但是，如果您想要扩展，破解或以其他方式弄乱编辑器的能力，那么您将失去一些性能。

Quite right!
I understand

**Comment by mauricioszabo** [comment]
So, any actionable items here? Can we close this issue?

**Comment by Daeraxa** [comment]
I agree to close. It is a discussion topic at most
