### ISSUE TITLE
Transient issue in Rolling Release that can cause: Regression - Packages no longer showing in latest rolling binary and cannot fetch packages from backend

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/pulsar#431]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Install latest Windows setup binary from CI - https://cirrus-ci.com/task/5425393881055232

Go to `Packages` - packages do not load.

Console errors: 

```
installed-packages-panel.js:204 Fetching local packages failed. Error: Fetching local packages failed.
    at file:///C:/Users/dae/AppData/Local/Programs/pulsar/resources/app.asar/node_modules/settings-view/lib/package-manager.coffee:94:17
    at exit (file:///C:/Users/dae/AppData/Local/Programs/pulsar/resources/app.asar/node_modules/settings-view/lib/package-manager.coffee:68:7)
    at triggerExitCallback (C:\Users\dae\AppData\Local\Programs\pulsar\resources\app.asar\src\buffered-process.js:280:9)
    at ChildProcess.<anonymous> (C:\Users\dae\AppData\Local\Programs\pulsar\resources\app.asar\src\buffered-process.js:310:9)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
(anonymous)	@	installed-packages-panel.js:204
processTicksAndRejections	@	internal/process/task_queues.js:93

package-manager.coffee:160 Uncaught (in promise) Error: Fetching outdated packages and themes failed.
    at package-manager.coffee:160
    at exit (package-manager.coffee:68)
    at triggerExitCallback (C:\Users\dae\AppDa…ered-process.js:280)
    at ChildProcess.<anonymous> (C:\Users\dae\AppDa…ered-process.js:310)
    at ChildProcess.emit (events.js:315)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277)
(anonymous)	@	package-manager.coffee:160
exit	@	package-manager.coffee:68
triggerExitCallback	@	C:\Users\dae\AppDa…ered-process.js:280
(anonymous)	@	C:\Users\dae\AppDa…ered-process.js:310
emit	@	events.js:315
ChildProcess._handle.onexit	@	internal/child_process.js:277
```

Go to `Install`
```
Fetching featured packages failed.Hide output…
node:internal/modules/cjs/loader:1167
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\dae\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\git-utils\build\Release\git.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1167:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (C:\Users\dae\AppData\Local\Programs\pulsar\resources\app\ppm\node_modules\git-utils\src\git.js:3:22)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Working fine in 1.103.0 and 1.102.2023031607.

### Pulsar version

1.103.2023031703

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

See previous

**Comment by FunkyEgg** [comment]
having this issue right now aswell

**Comment by confused-Techie** [comment]
Can confirm on Windows 10 (22H2) that I am able to replicate part of this issue.

I get the same error message when attempting to load local packages, but can not replicate the issue when loading the featured packages or even when searching for packages.

I thought this could be because of the featured packages being cached for 15 minutes, but I'm able to search for remote packages just fine. So it's not an issue of caching.

Looking at the code causing local packages to fail from `settings-view/lib/package-manager.coffee` here it is below:

```coffeescript
  loadInstalled: (callback) ->
    args = ['ls', '--json']
    errorMessage = 'Fetching local packages failed.'
    apmProcess = @runCommand args, (code, stdout, stderr) ->
      if code is 0
        try
          packages = JSON.parse(stdout) ? []
        catch parseError
          error = createJsonParseError(errorMessage, parseError, stdout)
          return callback(error)
        callback(null, packages)
      else
        error = new Error(errorMessage)
        error.stdout = stdout
        error.stderr = stderr
        callback(error)

    handleProcessErrors(apmProcess, errorMessage, callback)
```

Seems to be failing to execute a PPM command. Just weird it doesn't happen to me elsewhere.

Also another interesting note, is there is quite a significant size difference from `1.103.0` and the latest rolling release, that I wonder if it somehow factors into this.

* `1.102.0`: `0.97 GB`
* `1.103.0`: `1.06 GB`
* `1.103.2023031703`: `998 MB`

So we can see that the latest rolling is missing a bit of data from our last release. Now this could be that it's missing the newest `autocomplete-css` completions? But I'm not sure how that would've happened

**Comment by confused-Techie** [comment]
Alright, so I am still able to search, but unable to install any packages with native modules:

![image](https://user-images.githubusercontent.com/26921489/226167472-44c18c70-b75b-4c62-98fa-a6b905f55bf6.png)

So I've just triggered a manual rebuild of our master branch for the rolling releases.

Since as far as I can tell we've only had a single PR land between the time of our regular release and rolling, and that's to bump the version in the `package.json` which shouldn't cause this issue.

So lets let it rebuild and see if it was a transient issue at the very least, because if not we may need to dig a bit deeper and see what's gone wrong.

**Comment by confused-Techie** [comment]
@FunkyEgg @Daeraxa 
Can you both please try installing the latest rolling from [here](https://cirrus-ci.com/build/4693795728523264).

Just tested it, and rerunning our build has fixed these issues for me on Windows.

That is Pulsar 1.103.2023031910 is now fully functional for searching, and installing both packages with native modules, and fully JS packages.

It looks like this was a transient issue that we don't have to worry to much about, but is slightly concerning to say the least

**Comment by Daeraxa** [comment]
Yep this is looking much healthier.

> It looks like this was a transient issue that we don't have to worry to much about, but is slightly concerning to say the least

Honestly I think this is really really worrying, I know it is a one-off but if we cannot guarantee that our rolling builds are working properly and consistently then we have a real issue in our change to the release strategy. We absolutely have to keep an eye on this.

**Comment by Daeraxa** [comment]
The immediate issue has been resolved - do we close this or keep it open under an edited title and description to make sure this can't happen again?

**Comment by confused-Techie** [comment]
@Daeraxa Just realized this was still open. Went ahead and gave the title an update. I personally think we should be fine to close this issue, but if you feel otherwise then we can leave it open until further narrowing down what caused it.

**Comment by Daeraxa** [comment]
Sorry just saw this. If we think it is OK to close then we can and we can always re-open if it happens again and keep it open for investigation.

**Comment by Spiker985** [comment]
Closing for now. Can be reopened, or referenced later if it reoccurs.
