### ISSUE TITLE
Arguments to `path.basename` must be strings

### ISSUE THREAD

**Issue by TheHCJ** [pulsar-edit/pulsar#507]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I tried cloning a Github repo then got the error

```
Object.basename - [/Applications/Pulsar.app/Contents/Resources/app.asar/src/electron-shims.js:34:10](https://github.com/Applications/Pulsar.app/Contents/Resources/app.asar/src/electron-shims.js:34:10)
<unknown> - [/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/github/lib/views/clone-dialog.js:33:36](https://github.com/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/github/lib/views/clone-dialog.js:33:36)
Function.simpleDispatch - [/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/event-kit/dist/emitter.js:64:14](https://github.com/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/event-kit/dist/emitter.js:64:14)
Emitter.emit - [/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/event-kit/dist/emitter.js:257:28](https://github.com/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/event-kit/dist/emitter.js:257:28)
TextBuffer.emitDidChangeTextEvent - [/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:2374:24](https://github.com/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:2374:24)
TextBuffer.transact - [/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1337:10](https://github.com/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1337:10)
```

### Pulsar version

1.104.2023042015

### Which OS does this happen on?

🍎 macOS

### OS details

11.7.6 Big Sur

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Login with Github
2. Click `Clone existing Github repository...`

**Comment by Daeraxa** [comment]
Is there a particular repo that shows this? I just tried with a couple (e.g. `atom/atom`) and didn't have any issues.

**Comment by DeeDeeG** [comment]
I could not reproduce this issue, repositories clone fine for me from the github package's UI panel.

Tested on intel macOS 10.15.7, with Pulsar 1.104.0, 1.104.2023042015 (matches the bug report, I happened to have a copy of this version saved on my computer already), and the latest 1.104.2023050203.

Note that I had to type a repo's full URL, such as `https://github.com/DeeDeeG/mypackage11111` into the box indicating the URL to clone. This wasn't immediately obvious, but trial and error proved this worked, at least for me.

---

These bits from the error report are a little strange looking to me...

> `[/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1337:10](https://github.com/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1337:10)`

Is that a markdown-formatted link?... Hmm. But the URL it points to is very malformed/weird... "`https://github.com/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1337:10`"

It's an HTTPS url consisting of `https://github.com` with what looks like a line of a stack trace appended/grafted onto it `/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1337:10`

_Very strange._

---

Anyway, I don't really know how to get a closer look at what might have been going on here, since I can't reproduce it locally.

Best Regards,
\- DeeDeeG

**Comment by confused-Techie** [comment]
@DeeDeeG Thanks a ton for taking the time to test this one.

@TheHCJ Can you provide more information? Did you install any community packages? Or modify anything else about the application? Or otherwise was this a specific repo you tried to clone?

**Comment by TheHCJ** [comment]
Sorry for the late response, the bug seemed to go away after a restart. I
will now close this issue
