### ISSUE TITLE
Add .gradle format support

### ISSUE THREAD

**Issue by yhojann-cl** [pulsar-edit/pulsar#508]
### Have you checked for existing feature requests?

- [x] Completed

### Summary

Please add support for Java .gradle file syntax (eg for java spring boot).

### What benefits does this feature provide?

Edit configuration files for Java Spring.

### Any alternatives?

Without alternatives.

**Comment by confused-Techie** [comment]
@yhojann-cl There's a community package that seems to do this: [`language-gradle`](https://web.pulsar-edit.dev/packages/language-gradle)

Keep in mind the vast majority of things like autocompletions, or specific language support will come from community packages, and there's over 10,000 you should always take a look at the community packages available

**Comment by confused-Techie** [comment]
Since it's been over a week without any response, and this is a non-issue by the fact that this is already a community package, and doesn't need to be included into the core of the editor, I'll go ahead and close this one.

Thanks a ton for contributing @yhojann-cl and feel free to let us know if you have any troubles installing that package!
