### ISSUE TITLE
Hydrogen Package: New Python Modules Cannot be Found

### ISSUE THREAD

**Issue by rchaklashiya** [pulsar-edit/pulsar#519]
### Thanks in advance for your bug report!

- [ ] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

**Description of issue**
Hi, I'm having a weird issue where for python modules, new modules that I install give the "ModuleNotFoundError".  Any old modules I've installed in the past (a couple weeks ago) still work. I tested this out on a variety of different modules (from couchdb to pokemon) just to make sure it is not module-specific, and the same issue happens for all of these new modules I try to install.

**System**
Windows 11

**What I've tried:**
I doublechecked that the new modules are in the same path location as my old modules, so this is not an issue of where the module is located.
I also ran both with and without Hydrogen, and these both give the same result.
I also updated Pulsar and restarted my computer and this did not resolve the issue
I also checked to make sure my Windows computer is up to date, seems like there's no new updates to install on my Windows computer itself
Cannot try in safe mode as there's no way to run python code with an output without installing a package

Does anyone know how to resolve this issue? I would really appreciate it if this is fixed, as I cannot move further with what I want to do without resorting to using a different IDE that I don't like as much (Eclipse). 

### Pulsar version

1.104.2023050204

### Which OS does this happen on?

🪟 Windows

### OS details

Microsoft Windows 11 Home

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

0. Install a new package to the correct path folder via pip install (package name) in cmd
1. Open Pulsar
2. import a python package in a file
3. try to run the file (either by "scripts" or "hydrogen" or "python-run", all of them will do the same thing)
4. you will get the error "ModuleNotFound"

### Additional Information:

![image](https://user-images.githubusercontent.com/18043279/236687133-938dc5bc-d068-42f7-8173-779bda478339.png)

**Comment by confused-Techie** [comment]
So I gather this is an issue with the Hydrogen package.

Since there is no aspect of Pulsar itself that attempts or supports running Python code. So there's zero changes that can be made on Pulsar's end to troubleshoot the behavior like this of a third party package.

Essentially, once Pulsar gets a third party package up and running, for the most part any issues in functionality is up to that specific package to resolve.

What I'd really suggest is opening up an issue over on the [Hydrogen Package's Repo](https://github.com/nteract/hydrogen) to seek help with this, or you could always chime in on of our community areas to see if any other users of Hydrogen have had this issue.

But unfortunately I don't believe there is much we here at Pulsar are able to do to resolve this.

**Comment by confused-Techie** [comment]
Since like I mentioned this is an issue within Hydrogen, and it seems the original commented has never responded to my message, or created an issue over on Hydrogen, I'm going to go ahead and close this one.
