### ISSUE TITLE
Allow running APM / PPM commands

### ISSUE THREAD

**Issue by mauricioszabo** [pulsar-edit/pulsar#56]
Versions generated with `electron-builder` do not work correctly with APM - it gets installed on the Pulsar "resources" directory and we don't actually put that on PATH. I see two solutions for us on this case:

1. On some "post install" method, link the `apm` to the same PATH that `pulsar` gets. This will keep the same functionality that we have on Atom, or;
2. Make the command `pulsar` accept a different argument called `package` and then redirect this to `apm`. In this case, instead of typing `apm install <package>` we could type `pulsar package install <package>`

While number 1 will keep the same funcionality we have today, I feel that 2 may be desirable because we can change how we bundle APM in the future - we can rename to `ppm`, or we can use it internally on Pulsar instead, and nobody will feel anything is different

**Comment by Daeraxa** [comment]
I think avoiding clashes wherever possible with Atom is probably pretty high. There is a high chance that people trying Pulsar will already have Atom installed and I think it is just asking for trouble.

Option two I like a lot, it makes it feel more like it is part of Pulsar itself and as you say it gives a lot of flexibility (and I assume it wouldn't go anywhere near Atom's stuff). We could even come up with something suitably whimsically named if desired.

**Comment by Sertonix** [comment]
I like the second option more because it removes the apm/ppm naming issues. But there is a problem. Currently every argument after `pulsar` is interpreted as path to open. I see these variations:

1.1. paths to open are specified differently like `pulsar --open=<path>` and `pulsar package install <package>` would not start pulsar
1.2. A toggle option that prevents the start and an option to install/uninstall packages `pulsar --package-install=<package> --no-start`.
1.3. A toggle option that prevents the start of pulsar and interprets the arguments different. eg. `pulsar --package install <package>`.

**Comment by mauricioszabo** [comment]
Closed with https://github.com/pulsar-edit/pulsar/pull/125
