### ISSUE TITLE
Styleguide TypeError `grammar.onDidUpdate` is not a function

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/pulsar#560]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The error occur if Styleguide is opened and Pulsar is reloaded by `window:reload`.

### Pulsar version

1.105.2023052201

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open styleguide
2. Use `window:reload`

### Additional Information:

![image](https://github.com/pulsar-edit/pulsar/assets/29706474/774effff-317e-4dfa-90ca-8632a9debaae)

**Comment by savetheclocktower** [comment]
I've noticed this myself and even tried to narrow down the problem, but ultimately put it aside because it's not a huge priority. I'm 90% sure that it has to do with the order in which packages get activated, and `styleguide` not yet being able to assign a grammar to an HTML code block because `language-html` hasn't yet been activated, so I'll keep this open until I can get around to fixing it.

**Comment by confused-Techie** [comment]
@asiloisad Awesome work identifying where exactly this occurs.

As for the fix here, while I'm sure there's a very rad technical fix buried within the activation chain, or in the grammars. As for some stop gaps I do have some ideas on what we could do:

* We could set an activation hook within `styleguide`, so that it isn't actually required until the full environment is up, since afaik none of the grammars use this behavior, so should be up before the activation hooks are actually triggered. Although we would have to check if activation hooks are ignored for bundled packages. Since last time I looked into the preload behavior, I'm pretty sure all bundled packages that are properly deserialized and cached are preloaded, with no concern for activation hooks at all.
* The other possible solution, I wonder if we could simply catch this error, and now knowing what it is, where if this error is caught, we collapse all sections of the `styleguide`. Which is the behavior that occurs now anyway I'm pretty sure. Where we could just make that intended behavior without emitting an error or crashing the package.

**Comment by savetheclocktower** [comment]
I messed around with a `whenGrammarActivates`  method that returns a promise. Seems to do the trick. I'll see if I can get it cleaned up and PR'd.

**Comment by asiloisad** [comment]
I have tried set activation hook `html&js..:grammar-used`, but it doesn't resolve a problem
