### ISSUE TITLE
[settings-view] code injections of code blocks

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/pulsar#577]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

markdown preview & setting-view should use grammar injection to highlight code block (if used).

![image](https://github.com/pulsar-edit/pulsar/assets/29706474/0a8e2f32-1bcb-4eb4-9cb8-2932b17d0742)

![image](https://github.com/pulsar-edit/pulsar/assets/29706474/d8598f40-4f46-420b-9af7-c47e06770800)

### Links of example

https://github.com/bacadra/atom-project-files

https://web.pulsar-edit.dev/packages/project-files

### What benefits does this feature provide?

much better preview of markdown files with code injections

### Any alternatives?

Use another editor

### Other examples:

github.com
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/b5ce0d5d-a9bd-4886-9a64-43283ddb1636)

web.pulsar-edit.dev
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/c420b702-3562-4fdb-bb39-519ac2d27abd)

**Comment by savetheclocktower** [comment]
Try `coffeescript` instead of `cson`. If that works, then all we'd need to do is add an alias.

**Comment by asiloisad** [comment]
good point. `coffeescript` has resolved problem of `markdown-preview`, but settings-view does not highlight code still.
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/6d83ce27-72a1-446c-bf25-955c016b2666)

**Comment by confused-Techie** [comment]
Reading through I was going to say I thought Markdown-preview already did this. So glad we got that resolved.

But in that case this would be something good to add to `settings-view`

**Comment by confused-Techie** [comment]
So I've been looking at this again, and was surprised to see the implementation of code highlighting in `marked` (What `markdown-preview` uses) is more complex than I thought.

But more importantly, I've realized that `settings-view` purposefully removes any code formatting within a description.

From the Config API docs we can see where [it mentions](https://atom-flight-manual-archive.github.io/api/v1.57.0/Config/#title-and-description) that only a subset of markdown features are supported, this is because `settings-view` actually removes `marked`s ability to parse:

  * `code`
  * `blockquote`
  * `heading`
  * `html`

Which according to the [original discussion](https://github.com/atom/settings-view/pull/635) that blacklisted certain markdown features (also the first discussion to add Markdown support to setting's descriptions) we can see essentially they thought supporting everything was a bad idea. That it would be misused/abused. Which for some things I do agree with, such as images, or any arbitrary HTML element.

But I suppose the question comes down to, do we want to support code blocks within a setting's description?

I'd be fully happy to support inline code blocks, but that wouldn't let you choose a grammar at all, and normally grammars (at least in GitHub flavoured Markdown) aren't applied at all to inline code blocks.

So is this something we feel like we should add in? Or do we want to agree with the original maintainers on disallowing this behavior?

**Comment by confused-Techie** [comment]
Without much more talk about this issue, considering now that #622 resolves the issue of using `cson` or `coffeescript`, and that disallowing the usage of code blocks within `settings-view` is a purposeful decision, that I honestly agree with at this point.

But since nobody has spoken up about the want to remove some of this removed Markdown features, I'm inclined to close this as a won't fix. 

Thanks a ton for reporting this issue @asiloisad, and I'm glad we could get it partially resolved.
