### ISSUE TITLE
Selecting values from autocomplete drop-down not working all the time

### ISSUE THREAD

**Issue by m1ga** [pulsar-edit/pulsar#583]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

This one is a bit hard to reproduce since it doesn't happen all the time and I can't really say when it is broken or not (recorded a minute to have both bugs):

When I edit a e.g. CSS file and I want to select a value from the autocomplete drop-down it sometimes doesn't select the value but writes TAB or RETURN

Here I press TAB to select the value and it will add a TAB the second time:

https://github.com/pulsar-edit/pulsar/assets/4334997/7bb82ea9-40d2-48fe-a2de-78ec2d0fd73f

Here I press ENTER to select the value and it will add a new line:

https://github.com/pulsar-edit/pulsar/assets/4334997/f558e31b-43ce-46af-b947-1e8ca7e34023

second time works fine. I see it in other files too, so it is not a pure CSS issue.

### Pulsar version

1.105.0

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 38

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Edit a CSS file and autocomplete some values as seen in the video

**Comment by confused-Techie** [comment]
Sorry for responding so late, but thanks a ton for reporting this one! We will have to look into this one

**Comment by AlexWayfer** [comment]
I'm not sure if my problem is related or a separate one.

Original issue: https://github.com/pulsar-edit/package-backend/issues/194

My behavior:

* Type `attr` in a Ruby file, get the autocompletion list.
* Select something, get completing or not (read below how it depends)
  * If not — delete some chars and try again — you will get it now.
* Now if you will select the whole line via `Home` key, for example, retry autocompletion — it'll work.
* **But**, if you will press `Enter` (not when autocompletion list is showed) to go to a new line — you (or just I) will guaranteed get this bug, not-completing.

So, it breaks after `Enter` for a new line. Somehow.

Video: 
[Screencast from 2023-08-18 12-58-41.webm](https://github.com/pulsar-edit/package-backend/assets/6510020/1ea9a842-2366-404e-ba53-093f792e5ad0)

Difference with the original issue: there is nothing on `Tab` press, no tab (or spaces) symbols.

But I think I faced that issue too in CSS sometimes.

If you think I should create a separate issue, it's a different problem — OK.

**Comment by savetheclocktower** [comment]
@AlexWayfer, I think this is probably a similar issue to yours. If I get time I'll see if I can reproduce this myself.

**Comment by AlexWayfer** [comment]
> @AlexWayfer, I think this is probably a similar issue to yours. If I get time I'll see if I can reproduce this myself.

Thank you. It turns out to be very annoying, to be honest. Autocompletion is a core feature of any code editor, new lines are very often, and breaking all the time… I'm glad that I've discovered the precise reproduction steps. But if you need for more details — my pleasure to provide them.

**Comment by savetheclocktower** [comment]
@AlexWayfer, which package do you use that provides Ruby autocompletions? I'm trying to recreate the exact scenario from your screencast, even down to your specific `autocomplete-plus` settings.

**Comment by savetheclocktower** [comment]
I've found one bug already. @m1ga, I'm certain this'll fix your issue; @AlexWayfer, not quite as sure.

Here's what happens:

![autocomplete-menu-race-condition](https://github.com/pulsar-edit/pulsar/assets/3450/158b27d7-b818-44d1-88e5-1681a62ca98b)

After I autocomplete the property name, the menu disappears… and immediately re-appears. The key bindings for confirming a selection via <kbd>Tab</kbd> and/or <kbd>Return</kbd> are scoped to `atom-text-editor.autocomplete-active`. So when `autocomplete-plus` opens its menu, it adds that class name to its associated `atom-text-editor` element, and removes it when the menu closes. In theory! But those can get out of sync.

Atom lets us schedule DOM tasks in order to do efficient batching. So when a menu closes, and `autocomplete-plus` schedules the removal of the `autocomplete-active` class name, it doesn't consider that _by the time that code runs, we may not want to remove the class name anymore_. Because, for instance, the menu is already open again. So it removes the class name even though the menu is open.

Navigating the list works fine (because those are just core movement commands), but confirming a selection doesn't, because `autocomplete-plus` won't be chosen to receive that key binding when the expected class name isn't present. Instead, the editor responds, and inserts a tab character or newline. And `autocomplete-plus` says “hm, guess this menu isn't needed anymore,” and closes it.

This is an easy enough fix. In fact, the screencast above demonstrates that it's fixed. @AlexWayfer, I'm now not certain that your issue is related, because I can't identify a similar race condition in your example. But it'll be easy enough to test: when the PR for this fix lands, I'll ask you to download the next rolling release to see if that fixes your issue. Meanwhile, I'll keep trying to reproduce your scenario.

**Comment by m1ga** [comment]
oh wow, that sounds like the think that's happening! I didn't know that it sets classes otherwise I would have checked the devtools to see if it is out of sync. But that would explain why it is not happening all the time but sometimes when the timing is mixed up :+1: 

I'll test it once its merged

**Comment by AlexWayfer** [comment]
> @AlexWayfer, which package do you use that provides Ruby autocompletions? I'm trying to recreate the exact scenario from your screencast, even down to your specific `autocomplete-plus` settings.

[`solargraph`](https://web.pulsar-edit.dev/packages/ruby-solargraph)

(ironically, now it returns a server error, 505:
![image](https://github.com/pulsar-edit/pulsar/assets/6510020/18d4b058-abb5-463a-ae5b-d34921d04332)
)

---



> @AlexWayfer, I'm now not certain that your issue is related, because I can't identify a similar race condition in your example. But it'll be easy enough to test: when the PR for this fix lands, I'll ask you to download the next rolling release to see if that fixes your issue. Meanwhile, I'll keep trying to reproduce your scenario.

OK, I believe I'm ready to test.

**Comment by m1ga** [comment]
> (ironically, now it returns a server error, 505:

they are chatting about that in discord already. All pages produce the error currently

**Comment by confused-Techie** [comment]
> > (ironically, now it returns a server error, 505:
> 
> they are chatting about that in discord already. All pages produce the error currently

For what it's worth things seem to be good now. Seems we had a rouge instance get spun up, causing failures across tons of pages. Should be fine for now, although still investigating methods to remedy this
