### ISSUE TITLE
Allow reading/writing files from removable media

### ISSUE THREAD

**Issue by oneilmw** [pulsar-edit/pulsar#589]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Currently I store all of my computer science projects on a removable USB drive.
Using the Flatpak version, I am incapable of loading those project files into Pulsar.
I am able to load the root directory (/) into the Pulsar project navigation panel.
However, the /media folder is missing, which is where removable devices are mounted by default.
The same is true with the file manager it launches.  Currently it is using my default, nemo, though I doubt that's relevant, due to it likely propagating the issue from the permissions from Pulsar itself.

### What benefits does this feature provide?

The problem is that it fails to recognize the removable drives.

### Any alternatives?

I do not know of any "alternative" way of fixing this.  I do not know what that could possibly mean in this context.  The issue is that a region of storage is inaccessible.  I am requesting support to make that region accessible.

### Other examples:

Atom
geany
gedit
vs code
kate
GNOME text editor
TEA
GNU Emacs
Kwrite
Bluefish
It's a pretty standard thing IMO

**Comment by confused-Techie** [comment]
Does Atom successfully handle this use case? I see you listed it at the bottom of your issue.

Really, since Atom, there's nothing that I know of that we have changed at all with how files are read from disk, so I find it surprising that this now doesn't work. We really just use the built in, standard NodeJS `fs` module to read from disk, which if your default file handler doesn't see the file, I'm assuming `fs` is using the default system to read files, so could be exactly why this isn't working, as there are no extra special permissions within Pulsar that I'm aware of that would stop this from working.

So really this is rather a bug, than a feature request. As such would you mind providing some additional information, such as your operating system, version of Pulsar, as well if possible the file format of the drive, and your OS in general.

Thanks a ton for reaching out, and this additional info would be vital to trying to figure out what's going on here

**Comment by oneilmw** [comment]
OS: Debian 12
Platform: Flatpak
Pulsar version: 1.105.0

I can confirm that the flatpak version of Atom does allow editing from removable media.  The /media directory is viewable, and so are drives.
This feature does also work on the debian base package, 
Linux.pulsar_1.105.0_amd64.deb,
so this is likely a flatpak-exclusive issue.
My first place to consider looking is at the flatpak configuration.
The list at the bottom of the OP is of applications which support this feature.

**Comment by confused-Techie** [comment]
@oneilmw Oh I see. If this is indeed a Flatpak specific issue, the flatpak version of Pulsar is bundled and maintained completely by community members. None of the core dev team of Pulsar manages the flatpak version.

I'd suggest opening an issue with the maintainers of the flatpak version, as there won't be much we can do within Pulsar itself.

The repo that hosts the flatpak version of Pulsar is on [`flathub/dev.pulsar_edit.Pulsar`](https://github.com/flathub/dev.pulsar_edit.Pulsar)

**Comment by Daeraxa** [comment]
Just to add, yes, this will be flatpak specific due to the inherent "sandbox" nature of it - by default it won't be able to see a lot of stuff from your file system. I assume this is the difference between the Atom and Pulsar flatpak is that it is using a different manifest during install which allows the former to work but not the latter.

**Comment by oneilmw** [comment]
fixed flathub/dev.pulsar_edit.Pulsar/pull/9
