### ISSUE TITLE
Kaspersky (and others) identifies Pulsar as malware

### ISSUE THREAD

**Issue by pietrodicaprio** [pulsar-edit/pulsar#595]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I can't get Pulsar running due to Kaspersky blocking it for a `Hoax.JS.ExtMsg.a` presence.
Kaspersky is not the only one identifying a malware in Pulsar:
https://www.virustotal.com/gui/file/a79b7495fe78235cc215b79736080fee8bc3ef0c5aa04acbd8926d0b4aaf1397

Code Insight
`The code you provided is a JavaScript program that prints a message in Russian that calls for peace. The program does not appear to be malicious or harmful.`

### Pulsar version

Pulsar-1.105.2023061120-arm64

### Which OS does this happen on?

🍎 macOS

### OS details

Ventura 13.4

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

Download the rolling or the regular release, try to open it: App is damaged and can’t be opened

**Comment by Spiker985** [comment]
Can you confirm if this still occurs on version 106 that was just released?

**Comment by Spiker985** [comment]
It appears that the file in question is a `_postinstall.js` file

**Comment by pietrodicaprio** [comment]
Well, that's the reason: https://github.com/medikoo/es5-ext/issues/186
you should fork es5-ext and remove that message (show support to Ukraine using other methods...)

**Comment by Spiker985** [comment]
Yup, appears it's inside pulsar and ppm both
![image](https://github.com/pulsar-edit/pulsar/assets/7829451/13d597f8-d695-44c8-85fe-21b2656a8d00)

**Comment by pietrodicaprio** [comment]
downloading from the download page still provides v105 anyway

**Comment by Spiker985** [comment]
It does appear that the postinstall only executes on systems that have the following timezones:
> "Asia/Anadyr", "Asia/Barnaul", "Asia/Chita", "Asia/Irkutsk", "Asia/Kamchatka",
			"Asia/Khandyga", "Asia/Krasnoyarsk", "Asia/Magadan", "Asia/Novokuznetsk",
			"Asia/Novosibirsk", "Asia/Omsk", "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Tomsk",
			"Asia/Ust-Nera", "Asia/Vladivostok", "Asia/Yakutsk", "Asia/Yekaterinburg",
			"Europe/Astrakhan", "Europe/Kaliningrad", "Europe/Kirov", "Europe/Moscow",
			"Europe/Samara", "Europe/Saratov", "Europe/Simferopol", "Europe/Ulyanovsk",
			"Europe/Volgograd", "W-SU"

And would be stuck inside the Console - but this is still quite troubling

Especially since it has been there since 2022-03-07

**Comment by pietrodicaprio** [comment]
Indeed it's not executing on my system (CEST timezone) but the code is still checked and the execution of the entire program is not allowed. In the support section of Discord there is a post about Chrome's Advanced Protection blocking Pulsar download and that's probably for the same reason.

**Comment by confused-Techie** [comment]
So I want to add here, I'm taking a look at where or why we are including `es5-ext` within Pulsar. 

I'm pretty sure I've been able to track down what's causing it to be installed. Essentially, through a long line of dependencies, at one point we depend on [`property-accessors`](https://github.com/pulsar-edit/property-accessors) Which is one of our package's, had the dependency `es6-weak-map` which through another collection of dependencies, uses `es5-ext`. But about 7 years ago, this dependency was removed.

So ideally if we could get everything using the most modern versions of `property-accessor` then we should be able to stop relying on `es5-ext` within Pulsar itself. 

So really, it may be best to publish a new version of `property-accessors` on our NPM org, then afterwards find all usages of this and ensure they are all up to date.

It seems that `property-accessors` is depended on within:

  * [`atom-keymap@8.2.15`](https://github.com/pulsar-edit/atom-keymap)
  * [`emissary`](https://github.com/atom-archive/emissary) Which is an Atom repo, but for some reason we don't have it forked??

The other hardpart, is that we would have to ensure we are using the same version of `emissary` every where. Since right now we are using `emissary` within:

  * [`grim`](https://github.com/pulsar-edit/grim) Luckily, in recent versions `grim` no longer depends on `emissary` and instead uses `event-kit`. So we just need to update the version of `grim` being used by `scoped-property-store`
  * [`pathwatcher`](https://github.com/pulsar-edit/node-pathwatcher/tree/master)
  * [`second-mate`](https://github.com/pulsar-edit/second-mate)
  * [`text-buffer`](https://github.com/pulsar-edit/text-buffer)

So unfortunately, due to the extreme way in which Atom made everything rely on everything, it'll be a bit of a mess to remove this single dependency. But totally possible, and hopefully if we can address these issues within Pulsar, and figure out where the problem is in `ppm` then we can get rid of these concerns. Additionally, I want to mention, my guess is this issue stems from the `first-mate` dependency within PPM. Since `first-mate` was the basis of `second-mate` which like mentioned earlier needs to have an updated version of `emissary`. So ideally by updating `second-mate` and moving `ppm` to that new version (and making it compatible with `second-mate` we can remove the issue from there as well.

**Comment by DeeDeeG** [comment]
So weird that it just recently started being flagged, since as far as I can tell we've had a version of `es5-ext` with the message since we added yarn.lock way back in July 2022.

@confused-Techie's PR looks like a viable workaround for us being flagged.
