### ISSUE TITLE
Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

### ISSUE THREAD

**Issue by Akshit-Chilkoti** [pulsar-edit/pulsar#615]
### Thanks in advance for your bug report!

- [x] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [x] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [x] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [x] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When I clicked the CRLF button at the bottom of the screen I got an error:
![image](https://github.com/pulsar-edit/pulsar/assets/86488967/bbe82416-ef1e-4545-8682-631894c28385)

### Pulsar version

1.106.2023062623

### Which OS does this happen on?

🪟 Windows

### OS details

Microsoft Windows 7 [Version 6.1.7601]

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Just click the CRLF (Line Ending) button at the bottom of the screen and you will get this error.

### Additional Information:

![image](https://github.com/pulsar-edit/pulsar/assets/86488967/bbe82416-ef1e-4545-8682-631894c28385)

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this!

Unfortunately I can't seem to recreate this on my work PC, but will try again once on my dev machine. If possible in the meantime, would you mind copy pasting the full stack trace? Since the error seems to be informing us that an element is missing from what's expected to be there, and I'd suspect that's because either some weirdness of running on Windows 7, or it could be because of a community package modifying items within the editor. 

So it may also be a good idea to test this within safe mode, or at the very least go ahead and temporarily disable community packages

**Comment by Akshit-Chilkoti** [comment]
Thaks for ur reply, Ill try that and report it soon. Thanks

**Comment by confused-Techie** [comment]
Unfortunately, while the original reporter never got back to us on this one. I've been able to recreate the error:

```
Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

At C:\Users\USER_NAME_REDACTED\AppData\Local\Programs\pulsar\resources\app.asar\src\command-registry.js:388

TypeError: Cannot read property 'webkitMatchesSelector' of undefined
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:388:25)
    at CommandRegistry.dispatch (/app.asar/src/command-registry.js:292:17)
    at HTMLAnchorElement.<anonymous> (main.js:122:19)
```

I can only recreate this issue if the line ending selector status bar entry is clicked right after application launch, when the only panes available are those shown by the welcome package.

Since as soon as any text buffer is actually opened, then the button starts working as expected. And if once a text buffer has been opened, and you then close those buffers the button will disappear, ensuring it's not clicked. Even then, this is difficult to do. Out of 10 launches, there was only one launch where the button appeared without any text buffers available, where I could recreate this. 

So easy to say this is an extreme edge case, as far as I can tell.

The reason happens is within [`line-ending-selector`](https://github.com/pulsar-edit/pulsar/blob/master/packages/line-ending-selector/lib/main.js#L121) when the status bar entry is clicked, it asks `atom.workspace.getActiveTextEditor()` for the current active text editor, then dispatches a command with that value. So I think while we could investigate why the button may rarely be clickable, such as seeing if we increase the wait of the `debounce` call when updating the tile, I think the simplest solution is to catch the event of the current active text editor being null, and emit a notification asking the user to open a text editor pane to be able to determine the current line ending. 

Since realistically, with how infrequently I could recreate this, I don't see any way to ensure that an extended wait of a debounce call will fix it, as testing this rare edge case may be extremely difficult

**Comment by savetheclocktower** [comment]
Could we just prevent the element from appearing before any text editors are open? I don't think it has any value outside of the context of a text editor. The bug seems to be that we're showing it before it's useful.

**Comment by confused-Techie** [comment]
@savetheclocktower Sorry if it wasn't clear, there's significant amount of logic that already does that exactly. Where if no text editor is present it will not show or actively remove itself.

That's why I said, I can only reproduce it even appearing without an active text editor 1 out of 10 launches.

I've only ever been able to replicate line-ending-selector appearing without any active text editors once. 

So I'm not sure exactly how we can bring that down from 1% to 0%. Since I can't recreate it ever appearing reliably enough to test a fix. That's why I was suggesting to add handling for the error scenario instead, since otherwise any change we make, I have no idea how we would validate it's fixed this 1% chance of line-ending-selector appearing without an active text editor

**Comment by savetheclocktower** [comment]
> Sorry if it wasn't clear, there's significant amount of logic that already does that exactly.

Nah, I just didn't read closely enough.

**Comment by Akshit-Chilkoti** [comment]
Thanks for ur reply! I was able to solve it before u answered but still, thx!

**Comment by confused-Techie** [comment]
@Akshit-Chilkoti How did you solve this? Since this is still an issue that can effect others

**Comment by AlexWayfer** [comment]
I've got this error on a fresh install on Windows. 🤔 

### Versions

**Pulsar**: 1.113.2024011604 x64
**Electron**: 12.2.3
**OS**: Microsoft Windows 11 Home
**Thrown From**: Pulsar Core


### Stack Trace

Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

```
At C:\Users\alexw\AppData\Local\Programs\Pulsar\resources\app.asar\src\command-registry.js:388

TypeError: Cannot read property 'webkitMatchesSelector' of undefined
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:388:25)
    at CommandRegistry.dispatch (/app.asar/src/command-registry.js:292:17)
    at HTMLAnchorElement.<anonymous> (main.js:122:19)
```

### Commands

```
     -1:17.2.0 application:open-folder (atom-pane.pane.active)
     -1:02.3.0 project-find:show (atom-pane.pane.active)
     -0:55.6.0 core:backspace (input.hidden-input)
     -0:54 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```
