### ISSUE TITLE
Use require("electron").clipboard instead of require("clipboard")

### ISSUE THREAD

**Issue by hgolin91** [pulsar-edit/pulsar#633]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I do not know how to do it, can you help me?

atom core (1 deprecation)

Use require("electron").clipboard instead of require("clipboard")

Object.<anonymous> - [/opt/Pulsar/resources/app.asar/exports/clipboard.js:4:6](https://github.com/opt/Pulsar/resources/app.asar/exports/clipboard.js:4:6)
Object.<anonymous> - [/opt/Pulsar/resources/app.asar/exports/clipboard.js:11:3](https://github.com/opt/Pulsar/resources/app.asar/exports/clipboard.js:11:3)
Module._compile - [/opt/Pulsar/resources/app.asar/src/native-compile-cache.js:120:30](https://github.com/opt/Pulsar/resources/app.asar/src/native-compile-cache.js:120:30)
Object..js - [/opt/Pulsar/resources/app.asar/src/compile-cache.js:252:23](https://github.com/opt/Pulsar/resources/app.asar/src/compile-cache.js:252:23)
Module.load - [internal/modules/cjs/loader.js:935:32](https://github.com/pulsar-edit/pulsar/issues/internal/modules/cjs/loader.js:935:32)
Module._load - [internal/modules/cjs/loader.js:776:14](https://github.com/pulsar-edit/pulsar/issues/internal/modules/cjs/loader.js:776:14)

### Pulsar version

**Pulsar**: 1.106.2023071102 x64

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

**OS**: Ubuntu 22.04.2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

Failed to activate the data-atom package

### Additional Information:

**Thrown From**: [data-atom](https://github.com/lukemurray/data-atom) package 0.29.1

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this one!

But this error must be resolved within the community package itself. There's nothing within Pulsar that can be done to resolve it.

Looking at the repo I can see this error was first reported back in [2021](https://github.com/lukemurray/data-atom/issues/201), where the original maintainer has never commented any indication that they will work on this issue.

Additionally, right in the [readme](https://github.com/lukemurray/data-atom) of this package we can see the maintainer has added the following notice:

> Please note that this package is no longer maintained by me (time, focus etc.). It still works for simple use cases.
>
> If any one wants to jump in and start contributing please reach out.

So this likely means that if you want this package fixed, a community member like yourself will have to step up in order to do so.

If you did want to fix this error via a PR to the community package repo, the error message is detailing exactly how to fix it. To use `require("electron").clipboard` instead of `require("clipboard")`.

Looking at the repo we can see this error seems to be emitted from [`table-view.js`](https://github.com/lukemurray/data-atom/blob/2c17bcb05fff3e4adc3ea24a35dbc4a490f61fb1/lib/views/table-view.js#L5), which although it's using `import` rather than `require` the steps should be very similar.

Since there's nothing that can be done on Pulsar to resolve this, I'd recommend contacting the maintainer, or submitting a PR with the needed changes to go ahead and fix this package, and ensure they know you are working on Pulsar. Otherwise, if the maintainer is not willing to provide these updates, they can be made to your local install of the package to fix the issue for only you, or you can fork the package and publish an updated version as your own package. Which if you do please let us know.

Feel free to respond here if any further advice is needed, but otherwise as this doesn't pose an issue with Pulsar at all, and instead is the result of the maintainer ignoring a warning about this usage for over 7 years, I'll go ahead and close this one.

Again, thanks a ton for reporting the issue!
