### ISSUE TITLE
Missing dependencies in Pulsar packages

### ISSUE THREAD

**Issue by cat-master21** [pulsar-edit/pulsar#658]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

In _some_ packages in Pulsar, they require additional files, which Pulsar does not provide/depend on.
For example x-terminal-reloaded@14.2.1:
```
> prebuild-install || node scripts/install.js

make: Entering directory '/var/tmp/apm-install-dir-2023629-245-ph1obq.gtz3d/node_modules/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: Leaving directory '/var/tmp/apm-install-dir-2023629-245-ph1obq.gtz3d/node_modules/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build'

prebuild-install WARN install No prebuilt binaries found (target=12.2.3 runtime=electron arch=x64 libc= platform=linux)
(node:287) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
make: g++: No such file or directory
make: *** [pty.target.mk:117: Release/obj.target/pty/src/unix/pty.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/app/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 6.4.6-200.fc38.x86_64
gyp ERR! command "/app/Pulsar/resources/app/ppm/bin/node" "/app/Pulsar/resources/app/ppm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/tmp/apm-install-dir-2023629-245-ph1obq.gtz3d/node_modules/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
```
Or terminal-plus@0.14.5 which depends on git:
```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/jeremyramin/pty.js.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
This package installation experience is largely inconsistent, and the RPM package for example provides none of these tools
```
[pumpkinking@fedora ~]$ rpm -qp /home/pumpkinking/Downloads/Linux.pulsar-1.107.1.x86_64.rpm --requires
/bin/sh
/bin/sh
at-spi2-core
gtk3
libXScrnSaver
libXtst
libnotify
libuuid
nss
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
xdg-utils
```
Some packages however install just fine without an tools like GCC or Git.

I don't think this happens on Windows since most users won't have `g++` for example.

### Pulsar version

1.107.1

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 38

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Download latest RPM
2. Install RPM
3. Notice the package does not provide some things for some packages

### Additional Information:

Maybe something could be done to unify things more?

**Comment by confused-Techie** [comment]
There are some dependencies, that are outside of the scope really for Pulsar to install.

What you've referenced here, are not the dependencies directly needed for Pulsar, but for `node-gyp`, which are only needed in a small subset of packages.

Basically if you try to install a package that has a need to build native modules, you need the tools installed in order to compile those native modules. 

While we are still working to update our documentation, if you look at any of the issues related to installing Hydrogen, you'll see to build native modules there are some dependencies needed. Which Pulsar cannot install.

On Windows that means:
* Visual Studio 2019 (Soon to be able to be any version)
* Visual Studio - desktop C++ Workload
* Visual Studio - Windows 10 SDK (Soon to be either 10 or 11)
* Python 3.10

On Linux that is:
* Python 3.10
* `make`
* C/C++ compiler toolchain like GCC

On macOS that is:
* Python 3.10
* XCode Command Line Tools: Should install `clang`, `clang++`, `make`

Really you can look at [`node-gyp`](https://github.com/nodejs/node-gyp) for easier reference, while keeping in mind our version is very outdated, but in a few releases should be totally up to date with this library.

But realistically considering that these tools are probably needed for less than 2% of the packages available, and the big installs that they are it doesn't make much sense to install them with every release of Pulsar. What should happen though, is when the install fails, Pulsar should notify you that you need to install these tools, to leave it unambiguous. 

---

Also totally a side note, keep in mind that `x-terminal-reloaded` is the only terminal application that is known to work on Pulsar. `terminal-plus` and any other variants are known to not work.

**Comment by cat-master21** [comment]
Ah, so those are the other dependencies for some packages. Thanks for letting me know as I wasn't quite sure what this was.

**Comment by confused-Techie** [comment]
> I _believe_ we can close this one, right?

You are correct, think this one is sorted out. I'll go ahead and close it.

@cat-master21 Feel free to reopen if you feel it's not sorted, or need additional input. Thanks, as always, for contributing!
