### ISSUE TITLE
WSL Support for Windows

### ISSUE THREAD

**Issue by buggsdummy** [pulsar-edit/pulsar#661]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

It'd be nice to have support for browsing Windows Subsystem for Linux and the VM underneath as we are able to get to the share underneath in windows from the file explorer, but I'm not able to see it when I try to add project folders.

### What benefits does this feature provide?

Able to edit files in WSL

### Any alternatives?

There is none

### Other examples:

![Screenshot 2023-08-03 110323](https://github.com/pulsar-edit/pulsar/assets/1307764/0a329f7c-1b97-44c0-88f4-dbc52b99b6dd)

**Comment by Spiker985** [comment]
If on Windows 11, try navigating to `\\wsl.localhost\`
If on Windows 10, try navigating to `\\wsl$\`

These are the "local share" locations for all WSL distros (they are the same location), and there should be folders per distro you have installed

For instance, `\\wsl.localhost\Ubuntu` or `\\wsl$\Ubuntu` should work for you

Ideally this would be something to support outright. However, considering the age of electron that we're currently on (for now), it's most likely unsupported with the underlying APIs. If newer electron versions have a way to include those locations (since they are Windows-only), perhaps we would be able to add direct support for them

**Comment by buggsdummy** [comment]
It looks like it already works with W11.
