### ISSUE TITLE
C syntax highlight error for defined types with sizeof operator

### ISSUE THREAD

**Issue by Jesse-Cooper** [pulsar-edit/pulsar#681]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The syntax highlighting for user defined types does not always work.

In the image below the custom type `my_int_t` is correctly highlighted in blue on line 10 like the standard `int` type above. However, when using  the custom type with the `sizeof` operator `int` is correctly highlighted, but `my_int_t ` is not.

<img width="262" alt="Screenshot 2023-08-20 at 3 07 55 pm" src="https://github.com/pulsar-edit/pulsar/assets/82210929/25b9c258-bab1-4fff-827f-df3a6dba877b">

### Pulsar version

1.107.1

### Which OS does this happen on?

🍎 macOS

### OS details

13.2 (22D49)

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Create `C` file.
2. Paste code below:
```c
#include <stdlib.h>


typedef int my_int_t;


int main()
{
    int *a;
    my_int_t *b;

    a = malloc(sizeof(int));
    b = malloc(sizeof(my_int_t));

    return EXIT_SUCCESS;
}
```

**Comment by savetheclocktower** [comment]
As far as I can tell, this is expected behavior for the [`tree-sitter-c` parser](https://github.com/tree-sitter/tree-sitter-c). In the context of an argument to `sizeof`, all it knows is that `my_int_t` is an identifier.

At the same time, it can recognize `int` as a type in that context because `int` is a reserved word, and can only ever refer to a type.

If `sizeof` were only ever used with types, then we could add a rule that _always_ highlighted its argument as though it were a type. But `sizeof` can also be used with arrays, so that's not a safe assumption to make. Hence we'd need to do some manual lexical analysis — keeping track of what's been declared and doing some rudimentary scope resolution — to understand that `my_int_t` is a type on that particular line.

Ideally, something like [a language server](https://web.pulsar-edit.dev/packages/ide-cpp) could help us out by doing that work. Syntax highlighting is entirely self-contained within Pulsar right now, but we've got ideas about eventually letting language servers hook themselves into the syntax highlighting cycle in various ways.

If you know of another code editor that handles this the way you expect, I'd be interested in knowing which one.

**Comment by Jesse-Cooper** [comment]
Interesting, however, it does seem to pick up on defined types when they are made as pointers (image below line 16)

<img width="307" alt="Screenshot 2023-08-20 at 4 54 57 pm" src="https://github.com/pulsar-edit/pulsar/assets/82210929/7acdd660-b3aa-4947-b1f5-b8c40dbd6536">

**Comment by savetheclocktower** [comment]
You might find the [Tree-sitter playground](https://tree-sitter.github.io/tree-sitter/playground) or the [`tree-sitter-tools` package](https://web.pulsar-edit.dev/packages/tree-sitter-tools) interesting.

I don't know enough about C or about `tree-sitter-c` to know why the pointer example changes the calculus for the parser.

**Comment by savetheclocktower** [comment]
I tried this in VSCode and it seemed to recognize that `my_int_t` was a type.

I couldn't figure out exactly _how_ until after a bunch of trial and error: it assumes any identifier that ends in `_t` is a type.

Given my understanding of C conventions, that feels like a pretty safe assumption, and it's an easy change we could make. Would that work for you?

**Comment by Jesse-Cooper** [comment]
I'm happy with this change, thanks.

This would fix the issue for me personally as I always follow that convention, but I do know some people who leave the `_t` off.

**Comment by savetheclocktower** [comment]
This has been added to #677 and will be present in the 1.109 release. Thanks for the report!
