### ISSUE TITLE
[Feature Request] One Dark Pro Syntax

### ISSUE THREAD

**Issue by zhaolinlau** [pulsar-edit/pulsar#710]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

One Dark Pro Syntax is a popular and widely-used syntax theme or color scheme for code editors and integrated development environments (IDEs), notably in Visual Studio Code (VS Code).

### What benefits does this feature provide?

One Dark Pro Syntax provides a visually appealing, readable, and comfortable coding environment, which can enhance productivity and reduce eye strain during long coding sessions.

### Any alternatives?

https://github.com/Binaryify/OneDark-Pro

**Comment by confused-Techie** [comment]
Thanks a ton for contributing!

But taking a look at the available community packages, not sure if this fits the bill but: [`one-dark-pro-vivid-synax`](https://web.pulsar-edit.dev/packages/one-dark-pro-vivid-syntax).

Otherwise, I personally think this would be the best place for a member from the community to step in and create a community package that provides this syntax theme.

**Comment by Daeraxa** [comment]
What are the differences from One Dark? The repo itself seem to imply it is just a One Dark port:

> Atom's iconic One Dark theme, and one of the most installed [themes](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Installs) for VS Code!

**Comment by confused-Techie** [comment]
Alright, this has been open for a month now, and like @Daeraxa helpfully pointed out, and I agree with, it looks like VS Code's "One Dark Pro" syntax theme is truly a port of Atom's One Dark syntax theme, which is a built in theme already included in the editor.

With that said, and no further clarification from the original poster, I'll go ahead and close this one.
