### ISSUE TITLE
modern-tree-sitter JS grammar highlight

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/pulsar#744]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I'm glad the modern-tree-sitter is in progress, but some misbehaves has been observed. In my opinion, the best highlighting is use same color for same objects, then visual identification by human is smooth. A below i have paste some screenshots, where same thing has diffrent color in different scopes. I'm aware the the modern-tree-sitter is much more aware of context and try to applied better highlighting, but the old one has been much more strict with above rule. Best regards, SB

example 1: 
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/c70a254f-862a-45af-b8d3-18a5beedd176)

example 2:
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/3316e615-e814-4022-9d26-3f25a4077c73)

example 3:
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/e88cfdd9-351c-438b-80fc-db244df80ff0)

example 4:
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/6d955123-a394-44e0-addb-fd3163660337)

### Pulsar version

1.109.0

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Use pulsar with modern-tree-sitter 😎

**Comment by savetheclocktower** [comment]
This is not a final decision, but all these are intentional design choices.

Consider this code block:

```js
import { serializeLexerFragment } from "util";

let highlight = (tokens, context) => {
  let last = tokens.pop();
  let serialized = serializeLexerFragment(tokens);
  let highlighted = HTML_STRINGS.parse(serialized, context);
  return [highlighted, last];
}

highlight([], null);
```

Right now we have three different JavaScript grammars, and each one handles this code block differently:

* The TextMate-style JS grammar just isn't robust enough to be able to detect which things in JavaScript should be considered “variables.” It doesn't try. In this code block, only `serializeLexerFragment` (within the import) and the function parameters `tokens` and `context` get scoped with `variable`; nothing else is scoped as `variable` at all.
* The legacy Tree-sitter JS grammar is even more limited — only the `tokens` and `context` parameters are scoped as `variable`. The import isn't scoped at all.
* The modern Tree-sitter JS grammar, though it understands the code extremely well, still doesn't know enough to be able to establish a clear _and_ comprehensive rule on when something should be scoped as `variable` and when it shouldn't. It knows when something is an identifier, but if every identifier were treated as a variable, 80% of a source code file would be the same color, and that's not useful. The rule I settled on is to scope _declarations_ and _assignments_ with `variable` scope names, because those are unambiguous, and because it can help a user find where a variable came from. So all the tokens from the first example are scoped with `variable`, along with the declarations of `last`, `serialized`, and `highlighted`.

Your theme colors variables reddish-orange. You seem to be asking for certain examples to be colored like ordinary text, and that's fine. You can do an override in your user stylesheet:

```css
@import "syntax-variables";

.syntax--variable.syntax--assignment {
  color: @syntax-text-color;
}
```

This should cover all the cases in your screenshots. I don't think it will have any negative effects in other grammars, but if I'm wrong, you can restrict the above override to JavaScript:

```css
@import "syntax-variables";

.syntax--source.syntax--js .syntax--variable.syntax--assignment {
  color: @syntax-text-color;
}
```

I've considered making this configurable. But if we make it configurable, it'd probably be a setting on _each theme_, rather than on the JS grammar itself. Because otherwise we'd be telling our grammar not to add scope names to something because of a user's aesthetic preferences, and the presence of a `variable` scope name has applications beyond just syntax highlighting.

I'm re-classifying this as a feature request. I'm not sure if the issue will remain open or not, but this is a complex issue and I'm happy to keep discussing it even if this issue ends up closed.

**Comment by confused-Techie** [comment]
@asiloisad While I'm aware you've now closed the issue, I'm somewhat curious in exploring why this was seen as problematic.

Don't get me wrong, the first time I saw it, I was taken back, until I realized how much richer the meaning I could derive from this was, Since then, I've fallen in love with the ability to see not only what something was, but what it was doing. But I'm curious, was your major issue with this:

* The text was unstyled, and remained default colouring
* The colouring didn't match what was expected

Because for me, I'd say my only want in this area, is that the text has no colour, sometimes making it difficult to find. Whereas if we found an appropriate colour for it in our default themes, I'd be perfectly content in the rest of the functionality. If you feel at all the same way, maybe we can work to try and ensure everything is still being coloured (within reason). 

Since I know @savetheclocktower may not be the biggest user of the default themes, if they would be able to help get together some of the newer scope concepts that may exist, it'd be much more reasonable to take each theme on one by one to ensure everything still receives some colouring.

**Comment by asiloisad** [comment]
I think the proposed option is unnecessary work. Examples of backward colors compatible with the legacy TS would be appreciated and enough 👍 I will give a credit for new concept, but I'm feel uneasy with it now :)

**Comment by asiloisad** [comment]
After thinking about the proposed concept, however, I conclude that the only solution is to significantly simplify text coloring, because there is no way for a tree-sitter to be able to identify the same object in multiple contexts.

In this case, the proposed new idea is probably the best that can be achieved in good performance.
