### ISSUE TITLE
[Windows] add Pulsar file handler by default on new install

### ISSUE THREAD

**Issue by wesinator** [pulsar-edit/pulsar#748]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Pulsar should be suggested as an application for files by default, out of the box from a Windows install. 

The setting is https://github.com/pulsar-edit/pulsar/blob/5f3e40a2f5369f8cedad9ee42c747709241e34a1/packages/settings-view/lib/system-windows-panel.js#L52
https://github.com/atom/atom/issues/15644

When I installed a new instance of the package in Windows 10, I had a markdown (.md) file that I tried to open, it didn't associate or suggest Pulsar in the list of applications. I had to manually select the path of the application to add Pulsar as a default application.

To reproduce: 
 - Clean Windows 10
 - Create markdown .md file
 - Install Pulsar under local user
 - Open .md file

### What benefits does this feature provide?

Better OOBE on Windows. 

Add the file handler on install so that Pulsar is automatically suggested for opening text files.

### Any alternatives?

Workaround is to manually select the Pulsar application path when the Windows Open with dialog comes up.

**Comment by confused-Techie** [comment]
Thanks a ton for contributing!

But I'm going to say, I think your listed alternative is very inaccurate. The alternative, and recommended way to have Pulsar as a registered file handler is to enable this feature in the settings. There's no reason to do this manually, and since you've linked the code snippet for this option from `settings-view` this is something you seem to already be aware of. So just wanting to say, that's not at all a necessary or recommended alternative.

As for the feature request at hand, while I do understand that many applications do this automatically, I am personally rather against it. But of course I'd be happy to hear from other maintainers, users, or contributors on the topic.

From my perspective changes like this are modifying the registry of your system, and personally I'd rather we only do what is asked of us by our users. Especially considering that we have no easy way to preform cleanup during uninstall of these modifications to the registry.

Since personally, I find it jarring and honestly disrespectful of my platform that when I install a program it takes the liberty of adding itself to the right click menu and cluttering it up, or when an application enables itself to auto start on system boot. I think programs should do only what is explicitly asked of them. Doing anything else means the program assumes it's important enough to shove itself in a users face, which I'd really rather Pulsar not do this.

So as you can tell, I'd rather we not implement this feature. But of course I'm open to further discussion on other views. Or if we would like we could put this up to a poll, like we do anytime there's conflicting viewpoints between maintainers. Thanks again for contributing!
