### ISSUE TITLE
[symbols-view] Migration of `symbols-view-redux` into core (feedback requested)

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/pulsar#814]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

The next installment of the Tree-sitter series is going to cover the `symbols-view` refactor. I'm eager to show folks what's been done, but I'm hesitant to tell them to go install [symbols-view-redux](https://web.pulsar-edit.dev/packages/symbols-view-redux) on the repository when our goal is to bring it into core.

Relatedly: I’m starting to look for a job more urgently, and (if successful) will have less free time to devote to Pulsar, so I’d like to tie up major projects like these while I know I’ve still got time.

I'm opening this issue to figure out what the best strategy is for making `symbols-view-redux` a core package. I'm especially looking for feedback from fellow core team members, but I'm happy for others to chime in if they have opinions.

## Strategy 1: drop `symbols-view-redux` into core, retire `symbols-view`

This is the approach that was taken with `autocomplete-plus`. I wasn’t around for that migration, so I don’t know how much of a pain it was, but we can at least point to it as prior art.

### How?

1. We’d add `symbols-view-redux` to the main repo in a manner similar to how we’ve brought core packages into the main repo; the process would be quite similar, even though `symbols-view-redux` isn’t already a core package.
2. We’d remove `symbols-view` altogether. (Perhaps we could simply disable it by default, though I don’t know if that’s possible.)
3. `symbol-provider-ctags` and `symbol-provider-tree-sitter` would also join as new core packages.
4. Any non-default settings the user made for `symbols-view` could be migrated upon first activation of `symbols-view-redux`. Of the two settings that exist, one would be moved to the equivalent `symbols-view-redux` setting, and the other to an equivalent setting on `symbol-provider-ctags`.
5. If a user has remapped any of the `symbols-view` commands via their `keymap.cson`, we could (a) pop up a notification telling them to change those to point to `symbols-view-redux`; (b) migrate their keymap automatically and pop up a notification explaining what we did; or (c) register commands under the legacy name _and_ the new name so that those keymaps continue to work. I don’t know which approach is best and might do some research to see if `autocomplete-plus` had to solve similar problems.

### Pros

* Modular and containerized. New functionality, new name.
* Possibly easier to revert if something goes wrong.
* If it was good enough for `autocomplete-plus`, it’s good enough for us.

### Cons

* We live with the name `symbols-view-redux` indefinitely. I’m not in love with that name; I just chose it because there’s already a `symbols-view-plus` package in the repo. Feels weird for that name to persist indefinitely just because of a naming collision. (The alternative is to pretend that the package name _hasn’t_ changed, and to use the old `symbols-view` name when defining command and setting names, but that feels… transgressive?)
* Relatedly: the core commands will have different names than those of the old package. That has implications for keymaps, and also (much less urgently) for stupid Pulsar-user tricks like one might find in fancy `init.js` files (such as invoking one command from another). Ideally, the change to the new version happens seamlessly, but that’s a bit trickier to provide with Strategy 1. I’m not in love with any of the options I brainstormed above for how to handle keymap migration.

### Unknown

* What happens if someone has installed `symbols-view-redux` as a community package? What does that first launch look like after downloading the version of Pulsar that has added `symbols-view-redux` to core?

## Strategy 2: modify `symbols-view` in place

I imagine `autocomplete-plus` was migrated the way it was because it started as a competitor to the core `autocomplete` package, so the decision to keep it as `autocomplete-plus` might’ve only been made because it was judged to be the least disruptive option. We don’t necessarily have to be so formal for a package that was always intended to be adopted by core.

### How?

1. We’d basically hollow out `symbols-view` and put new code into it. All code in `symbols-view-redux` that refers to the package’s name would be modified to refer to `symbols-view` instead. This saves us from having to decide whether to remove or disable the original `symbols-view`.
2. `symbol-provider-ctags` and `symbol-provider-tree-sitter` would still join as new core packages.
3. Settings migration would proceed very similarly to that of Strategy 1. On activation, we’d check for the presence of the “Use Editor Gramar As Ctags Language” option; if it’s present, we’d know that this user’s settings haven’t been migrated. That specific setting would be converted to its `symbol-provider-ctags` equivalent; the “Quick Jump To File Symbol” setting could remain as-is.

### Pros

* We don’t have to be reminded of this awkward refactor by staring at the word `redux` in various contexts.
* We don’t need to decide how to phase out `symbols-view`; we’d just change it in place.
* Keymaps wouldn’t need to be migrated.

### Cons

* The PR that performed this change wouldn’t be the prettiest thing you’ve ever seen.
* If the user were a curmudgeon and just wanted the old package back, it wouldn’t be as simple as disabling the new one and reactivating (or somehow reinstalling) the old one. I don’t know if this is a valid concern, or if anyone had nostalgia for the original core `autocomplete` package, but I suppose it’s possible.

### Unknown

* As above, I suppose we should consider what happens if a user already has  `symbols-view-redux` installed. I suppose that Strategy 2 makes this a bit trickier, and we’d need to figure out a way for `symbols-view-redux` to determine that the core `symbols-view` package is now smarter. Or maybe we wouldn’t! Hell, `symbols-view-redux` has been downloaded only 32 times. Maybe this isn’t a serious problem.

## Your turn

Weigh these options and let me know which one sounds better. I’ve got my own thoughts, but I’ll leave them below in a comment so as not to put my thumb on the scale.

### What benefits does this feature provide?

Better symbol navigation.

### Any alternatives?

Yeah, the two options I listed above.

**Comment by savetheclocktower** [comment]
My slight preference is for Strategy 2, and if nobody has an opinion in either direction, that's probably what I'll end up doing. But I'm eager to hear other viewpoints.

**Comment by Daeraxa** [comment]
If we, hypothetically, wanted to do something similar to the modern tree-sitter implementation would option 1 be the only realistic option to use (i.e. a settings option to move to the new symbols-view)? Not saying this makes sense but just wanted to cover it off.

Otherwise I am more in favour of option 2 as I agree it makes more sense to upgrade the functionality of an existing package and keep its original name than it does to just create extra appended items to it.

**Comment by confused-Techie** [comment]
Alternatively to @Daeraxa I'd personally say we introduce `symbols-view-redux` as a brand new core package. Disabling if possible or otherwise removing `symbols-view`.

Since from my perspective this has major differences to the Tree-Sitter change. Whereas Tree-Sitter was the introduction of a new grammar system, where there where technically already Legacy Tree-Sitter, TextMate, and the Null Grammar, this was a new addition. Meanwhile this change is seems to be a complete rewrite of the package and breaking it out into several pieces.

Since like you mentioned we would already be including:
* `symbol-provider-ctags`
* `symbol-provider-tree-sitter`

As brand new packages, introducing another one doesn't seem far fetched.

Although like you mention there is already the big issue of porting any settings changes over.

I feel like this may be a good of time as any, to find a system where we can implement a reusable method of porting settings from one thing to another. Whether this be from a package to another, or from a name to a new one. A system like this could be a new core package, or something baked into Pulsar core, but I know we have talked about the difficulty in this space before, so if we have a compelling reason to solve it, while doing other big changes, seems smart to get two birds with one stone so to speak. I'd be more than happy to focus on a change like this once back from vacation, but not sure the time frame you are working with wanting to get these changes in. 

But all that to say, I'd think these should be brand new packages, and we do our best to port settings from one to another. Really this viewpoint is only supported by the fact that this is such a significant change, it doesn't feel like an update or change of the original package, it seems like a new better implementation, and should be treated as such.

But so far I'm in the minority, so if that stays true then feel free to go with Strategy 2 instead with no worries here.

**Comment by mauricioszabo** [comment]
As for me - I prefer strongly the option `2`. I would also add that it could be a good idea for us to publish a package called `atom-symbols-view` with all the old Symbols View code, so that if someone wants to keep the old package working, they could.

**Comment by savetheclocktower** [comment]
I realized there's a compromise option: I'd asked @confused-Techie not to bring `symbols-view` into core just yet because of the refactoring work. It still references the `pulsar-edit/symbols-view` repo. So I could do this:

* Create a `packages/symbols-view` directory in the `pulsar` project
* Copy the contents of `symbols-view-redux` into it
* Rename all `symbols-view-redux` references to `symbols-view`
* Update the `package.json` at the root of the `pulsar` project to point to `packages/symbols-view` instead of referencing an external repo

If anyone thinks that'd be a horrible idea, please let me know.

**Comment by savetheclocktower** [comment]
OK, here’s a rough list of things that need to happen in some order:

* [ ] Rename [pulsar-edit/symbols-view](https://github.com/pulsar-edit/symbols-view) — at least in the `package.json`, if not the repo name itself. Figure out how to publish it to the package repo under its new name and the `pulsar-edit` username. Maybe `atom-symbols-view` or `symbols-view-legacy` or something.
* [ ] Bring `symbol-provider-ctags` and `symbol-provider-tree-sitter` into Pulsar as core packages.
* [ ] Create a new folder for `packages/symbols-view`, put the contents of the existing `symbols-view-redux` repo into that folder, and rename all `symbols-view-redux` references to `symbols-view`.
* [ ] Ensure all tests pass on each of the three new packages. (I’ll do this on my machine as a sanity check.)
* [ ] Ideally, get a Windows user to review that PR manually.
* [ ] Create a PR with all this work and ensure that CI passes. If it doesn’t, figure out why.

The first item might be the biggest unknown. Have we done this before?

**Comment by confused-Techie** [comment]
@savetheclocktower Are we good to close this one now?

**Comment by savetheclocktower** [comment]
Yes.
