### ISSUE TITLE
Issue with a package compatibility/support on Pulsar

### ISSUE THREAD

**Issue by hardRockWorld** [pulsar-edit/pulsar#817]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I had installed the volar package in Pulsar Ide and it works fine, but it gives me an error while trying to save the file. 
![volar-package-error-pulsar](https://github.com/pulsar-edit/pulsar/assets/82425081/4601e831-660d-4154-a36a-2d270b59b370)

### Pulsar version

1.111.2023112116

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

KDE Neon version 5.27

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. in the vuejs 3 environment that has a package called atom-ide-volar
2. config has vue detection and javascript detection
3. when I save the file it throws this error
4. ![volar-package-error-pulsar](https://github.com/pulsar-edit/pulsar/assets/82425081/6d3a04cd-6f11-4e68-8dfe-1ed6c43b5f74)

### Additional Information:

why is this package atom-ide-volar incompatible with the latest pulsar version?

**Comment by savetheclocktower** [comment]
You report problems with `atom-ide-volar`, but the errors in the screenshots are happening inside of `atom-ide-vue`.

If I had to guess, I'd say this error is happening because `atom-ide-vue`'s dependencies are declared using `^` before the version numbers, meaning it's willing to install any versions of those packages that share the same major version. I'm willing to bet that the newest `vscode-jsonrpc` is more strict about what it wants from a language server than what the installed version of `vls` is providing.

Annoyingly, this is a common problem with NPM packages. If this package is working properly in Atom, I'd suggest going into `~/.pulsar/packages` and deleting the `atom-ide-vue` folder, then copying `~/.atom/packages/atom-ide-vue` into `~/.pulsar/packages`.

**Comment by savetheclocktower** [comment]
I'm going to close this for now. If the problem persists, please open a new issue.

I've also been going through the IDE provider packages and making experimental updated versions (see (https://web.pulsar-edit.dev/packages/pulsar-ide-typescript-alpha)[pulsar-ide-typescript-alpha]), so I could certainly put `atom-ide-volar` onto that list.
