### ISSUE TITLE
 Syntax highlighting in `language-gfm`: four dashes (----) not colored

### ISSUE THREAD

**Issue by luixxiul** [pulsar-edit/pulsar#888]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

For https://github.com/pulsar-edit/pulsar/issues/878

Four dashes (`----`) are not colored with TreeSitterParsers enabled.

![Screenshot from 2024-01-21 16-31-58](https://github.com/pulsar-edit/pulsar/assets/3362943/61bb31cb-68ba-4444-a563-f8c58a37d912)

### Pulsar version

1.113.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Ubuntu

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Add below to `config.cson`:
````
".gfm.source":
  core:
    useTreeSitterParsers: true
````
2. Create a new file with GitHub Markdown
3. Write `----`

**Comment by confused-Techie** [comment]
Thanks for contributing!

I'd highly recommend adding this to the MEGA-ISSUE for `language-gfm` #878 as we are using those to track any syntax issues after the release of 1.113.0. Then closing this one.

Thanks a ton!

**Comment by savetheclocktower** [comment]
Closing in favor of #878, but I just addressed this [in this commit](https://github.com/pulsar-edit/pulsar/pull/859/commits/ee220dd6efd578c4e42374e076221c0c07997698). You'll get the original appearance automatically if you're using one of the built-in syntax themes; otherwise your community syntax theme will have to add styles for the `markup.horizontal-rule` scope in a manner similar to what you see in that commit.

If your theme is no longer maintained, you can make a similar change in your user stylesheet instead; ask for help in #878 if you want it.

Thanks for the report!
