### ISSUE TITLE
Not able to folder %w notation created Ruby arrays

### ISSUE THREAD

**Issue by Roko131** [pulsar-edit/pulsar#945]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Pulsar not recognizing `%w` notations arrays as array, therefore not being able to folder them.
(%w notation is a [different way](https://docs.ruby-lang.org/en/3.0/syntax/literals_rdoc.html#label-Percent+Strings) in ruby to create arrays)

`Atom v 1.60` does recognizing %w notations so in _Atom_ I'm able to folder it, this bug only happens in _Pulsar_

Expanded:
![image](https://github.com/pulsar-edit/pulsar/assets/3532929/a60abc92-0d9f-46cf-ad7d-d1925e828bc5)
Foldered:
![image](https://github.com/pulsar-edit/pulsar/assets/3532929/71b8d440-89b5-4078-8fce-945aa6a41087)

### Pulsar version

1.114.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Pop Os 22.04

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Open a new Ruby file, i.e. `myfile.rb`
2. Create 2 arrays, one using regular syntax, second using %w notation syntax:
```ruby
arr1 = [
  'str1',
  'str2',
  'str3',
]
arr2 = %w[
  str1
  str2
  str3
]
```
3. Notice you can only folder arr1, but not arr2

### Additional Information:

There are [other notations](https://docs.ruby-lang.org/en/3.0/syntax/literals_rdoc.html#label-Percent+Strings) besides %w, 
Same bug apply for any of them (foldable in _Atom_, not in _Pulsar_):

- %i Array of Symbols
- %q String
- %r Regular Expression
- %s Symbol
- %w Array of Strings
- %x Backtick (capture subshell result)

**Comment by savetheclocktower** [comment]
This should be a quick fix; it'll be ready for 1.115 in mid-March. Thanks for the report!

**Comment by savetheclocktower** [comment]
The commit above should fix this. It'll land right before 1.115 is released. Thanks again!

**Comment by Roko131** [comment]
Thank you, I took a look at the commit. just to make sure we get all the cases:
From the [docs](https://docs.ruby-lang.org/en/3.0/syntax/literals_rdoc.html) (bottom page, last row):
- If you are using “(”, “[”, “{”, “<” you must close it with “)”, “]”, “}”, “>” respectively.
- You may use most other non-alphanumeric characters for percent string delimiters such as “%”, “|”, “^”, etc.

So the way I see it:

it's for either:
- w
- W
- i
- I

And for each of them, to open we can use parentheses:
- ()
- []
- {}
- <>

And lastly `most other non-alphanumeric characters`... so just to name a **few** (all work in atom `v 1.60`):
```md
- '
- "
- ^
- %
- |
- $
- <space> hmm probably only make sense to use in a single line
- #
- @
- *
- Etc...................
```


```ruby
# some examples using 'w' but they would also work using 'W' 'I' or 'i'
ar = %w[
  st1
  st2
]

ar = %w{
  st1
  st2
}

ar = %w'
  st1
  st2
'
ar = %w"
  st1
  st2
"

ar = %w%
  st1
  st2
%

ar = %w@
  st1
  st2
@

ar = %w!
  st1
  st2
!

ar = %w!
  st1
  st2
!

ar = %w*
  st1
  st2
*
```

Oh and one last thing, not sure it it's a typo or not:
Comment says ` ; Handle %w[ and %i[`. but code below has `"%w(" "%i("`
It could be that I just don't understand how it works though
![image](https://github.com/pulsar-edit/pulsar/assets/3532929/2ad063fe-d307-455f-951b-0e0c09f1fb2a)

**Comment by savetheclocktower** [comment]
> Thank you, I took a look at the commit. just to make sure we get all the cases:

Yes, these will be covered. Of the special percent notations: 

* only `%w` and `%i` make sense as folding candidates, since the others are used to define strings
* Tree-sitter will mark them the same way no matter which characters are used as delimiters (allowing us to target the node types `string_array` and `symbol_array` for the folds

Of the changes to `highlights.scm` you see in that commit:

* The `tree-sitter-ruby` parser incorrectly marks the opening delimiter of a `%w` as `%w(`, no matter which character is used as a delimiter; this also applies to the closing `)`. It also marks the opening delimiter of a `%W` as `%w(`, ignoring the difference in case. The `%i` syntax has the same issue. This isn't a huge problem; all it affects is how we target this node in a Tree-sitter query. Technically, it's not good Tree-sitter practice, but it does make our lives easier that we don't have to write a separate query for every single possible delimiter permutation.
* Because of the above behavior, even something like `%W{` will still get targeted properly.
* We usually mark delimiters with scope names that describe the delimiter itself, hence the scope names with `bracket.round` and `bracket.square`. But because the delimiters can be so many different things, we also define a fallback scope name for punctuation that omits any description of the characters.
